#flutter version = 3.27.3

name: salon_2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  intl: ^0.20.2
  carousel_slider: ^5.0.0
  get_storage: ^2.1.1
  im_stepper: ^1.0.1+1
  pinput: ^5.0.1
  intl_phone_field: ^3.2.0
  http: ^1.3.0
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  fluttertoast: ^8.2.12
  flutter_stripe: ^10.0.0
  razorpay_flutter: ^1.4.0
  in_app_purchase: ^3.2.1
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  in_app_purchase_storekit: ^0.3.22+1
  clipboard: ^0.1.3
  speech_to_text: ^7.0.0
  dotted_border: ^2.1.0
  salomon_bottom_bar: ^3.3.2
  scroll_page_view: ^1.0.2
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  in_app_review: ^2.0.10
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  flutter_staggered_animations: ^1.1.1
  google_sign_in: ^6.3.0
  #  flutterwave_standard: ^1.0.8
  geolocator: ^10.0.0
  cached_network_image: ^3.4.1
  country_code_picker: ^3.3.0
  firebase_crashlytics: ^4.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/
    - assets/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  fonts:
    - family: SF-Pro-Display-Black
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Black.ttf
    - family: SF-Pro-Display-Bold
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Bold.OTF
    - family: SF-Pro-Display-Heavy
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Heavy.ttf
    - family: SF-Pro-Display-Medium
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Medium.otf
    - family: SF-Pro-Display-Regular
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Regular.ttf
    - family: SF-Pro-Display-SemiBold
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-SemiBold.ttf
    - family: SF-Pro-Display-Ultralight
      fonts:
        - asset: fonts/SFProDisplay/SF-Pro-Display-Ultralight.ttf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
