/**
 * Copy interface Skedisy — salon panel (menus, dashboard, actions, toasts).
 * Référence : AUTHENTICITE_SKEDISY.md
 */
export const SKEDISY_SALON_UI = {
  brand: "Skedisy",
  roleSalon: "Salon",
  loading: "Chargement…",
  breadcrumbHome: "Tableau de bord",
  nav: {
    menu: "Menu",
    expert: "Équipe",
    order: "Commandes",
    services: "Prestations",
    ecommerce: "Boutique",
    finance: "Finances",
    report: "Rapports",
    dashboard: "Tableau de bord",
    experts: "Coiffeur·se·s / pros",
    reviews: "Avis",
    complaints: "Réclamations",
    attendance: "Présences",
    orders: "Commandes",
    products: "Produits",
    attributes: "Attributs",
    withdraw: "Demande de retrait",
    wallet: "Portefeuille",
    walletHistory: "Historique portefeuille",
    salonTime: "Horaires salon",
    salonHoliday: "Fermetures / congés",
    teamCalendar: "Planning équipe",
    paymentSettings: "Paiements Stripe",
    logout: "Déconnexion",
  },
  dashboard: {
    title: "Vue d'ensemble",
    welcome: "Bon retour sur votre espace salon",
    totalExperts: "Pros actifs",
    completedBooking: "Réservations terminées",
    totalRevenue: "Chiffre d'affaires",
    salesCommission: "Commission Skedisy",
    dataAnalysis: "Analyse",
    revenueBookingChart: "Revenus et réservations",
    upcomingOrders: "Commandes à venir",
    recentOrders: "Activité commandes récente",
    topExperts: "Meilleurs pros",
    viewAll: "Tout voir",
    todayBookings: "Réservations du jour",
    teamCalendarCta: "Voir le planning équipe",
    teamCalendarHint: "RDV, créneaux libres et indisponibilités en temps réel",
    paymentSettingsCta: "Configurer les paiements (espèces / Stripe)",
    paymentSettingsHint:
      "Recevez les paiements carte directement sur votre compte Stripe Connect",
    showMore: "Voir plus",
    fallbackUser: "Cliente",
    price: "Prix :",
    quantity: "Quantité :",
  },
  table: {
    no: "N°",
    expert: "Pro / coiffeur·se",
    bookings: "Réservations",
    expertEarning: "Gains pro",
    salonCommission: "Commission salon",
    user: "Cliente",
    time: "Heure",
    name: "Nom",
    image: "Photo",
    showMore: "Voir plus",
    service: "Prestation",
    bookingId: "N° réservation",
    duration: "Durée",
    date: "Date",
    status: "Statut",
    firstSlot: "Créneau",
    action: "Action",
    details: "Détails",
    createdAt: "Créé le",
    finalAmount: "Montant final",
    salonEarning: "Gain salon",
    email: "Email",
    mobile: "Tél.",
    rating: "Note",
    price: "Prix",
    adminCommission: "Commission plateforme",
    confirm: "Confirmer",
    info: "Infos",
    present: "Présent",
    absent: "Absent",
    pay: "Payer",
    day: "Jour",
    openTime: "Ouverture",
    closeTime: "Fermeture",
    breakStart: "Début pause",
    breakEnd: "Fin pause",
    edit: "Modifier",
    totalBookings: "Total réservations",
    paidPayment: "Montant payé",
    serviceEarning: "Gains prestations",
    bonusPenalty: "Bonus / pénalité",
    settlementMonth: "Mois de règlement",
    paymentDate: "Date paiement",
    paymentMode: "Mode de paiement",
    transactionType: "Type",
    transactionCompleted: "Terminé",
    uniqueId: "Référence",
    credit: "Crédit",
    debit: "Débit",
    productCode: "Code produit",
    brand: "Marque",
    category: "Catégorie",
    mrp: "Prix public",
    shipping: "Livraison",
    outOfStock: "Rupture",
    trending: "Tendance",
    newCollection: "Nouveauté",
    block: "Bloquer",
    platformFee: "Frais plateforme (%)",
    active: "Actif",
    schedule: "Planning",
    order: "Commande",
    srNo: "N°",
    expertImage: "Photo pro",
    salonImage: "Photo salon",
    userImage: "Photo cliente",
    expertName: "Nom du pro",
    salonName: "Nom du salon",
    userName: "Nom cliente",
    firstName: "Prénom",
    lastName: "Nom",
    accept: "Accepter",
    reject: "Refuser",
    isActive: "Actif",
    product: "Produit",
    createStatus: "Statut création",
    orderId: "N° commande",
    userInfo: "Cliente",
    items: "Articles",
    reason: "Motif",
    closedTime: "Fermé à",
    review: "Avis",
    categoryName: "Catégorie",
    country: "Pays",
    bestSeller: "Meilleures ventes",
    booking: "Réservation",
    delete: "Supprimer",
    about: "À propos",
    commission: "Commission",
    salonCommissionPct: "Commission salon (%)",
    adminEarning: "Gains plateforme",
    earning: "Gain",
    earnings: "Gains",
    earningsExpert: "Gains (pro)",
    earningsAdmin: "Gains (plateforme)",
    amount: "Montant",
    payoutMonth: "Mois de paiement",
    paymentStatus: "Statut paiement",
    settlementType: "Type règlement",
    settlementDate: "Date règlement",
    transactionDetails: "Détail transaction",
    quantity: "Quantité",
    month: "Mois",
    monthYear: "Mois / année",
    note: "Note",
    notification: "Notification",
    total: "Total",
    totalExperts: "Total pros",
    totalDays: "Total jours",
    totalEarning: "Gain total",
    totalPrice: "Prix total",
    totalRevenue: "Revenu total",
    totalCompletedBookings: "Réservations terminées",
    totalPaymentToExpert: "Paiement au pro",
    noBooking: "Nb réservations",
    noExperts: "Nb pros",
    serviceAmount: "Montant prestations",
    servicesAmountPlus: "Prestations +",
    adminEarningPlus: "Gains plateforme +",
    expertEarningPlus: "Gains pro +",
    salonEarningPlus: "Gains salon +",
    taxEquals: "Taxe =",
    tax: "Taxe",
    taxPlus: "Taxe +",
    plus: "+",
    eq: "=",
    deliveredService: "Prestation réalisée",
    itemDetail: "Détail article",
    bookedAt: "Réservé le",
    cities: "Villes",
    absentDays: "Jours d'absence",
    availableDays: "Jours disponibles",
    allAttendanceInfo: "Présences",
    salon: "Salon",
    gender: "Genre",
    claimStatus: "Réclamation fiche",
    expertInfo: "Infos pro",
    title: "Titre",
    description: "Description",
    code: "Code",
    invoice: "Facture",
    discountPct: "Remise (%)",
    maxDiscount: "Remise max.",
    paymentType: "Type de paiement",
    salonUserFallback: "Compte salon",
  },
  status: {
    completed: "Terminée",
    confirm: "Confirmée",
    cancel: "Annulée",
    pending: "En attente",
    complete: "Terminée",
    orderConfirmed: "Commande confirmée",
  },
  actions: {
    addExpert: "Ajouter un·e pro",
    addProduct: "Ajouter un produit",
    addAttribute: "Ajouter un attribut",
    addCategory: "Ajouter une catégorie",
    addService: "Ajouter une prestation",
    newHoliday: "Nouveau congé",
    pdf: "PDF",
    csv: "CSV",
    excel: "Excel",
    print: "Imprimer",
    processing: "Traitement…",
  },
  analytics: {
    all: "Tout",
    today: "Aujourd'hui",
    yesterday: "Hier",
    last7: "7 derniers jours",
    last30: "30 derniers jours",
    thisMonth: "Ce mois-ci",
    lastMonth: "Mois dernier",
    rangeTo: "au",
    selectDate: "Choisir une date",
  },
  wallet: {
    title: "Portefeuille",
    balance: "Solde portefeuille",
    minBalance: "Solde minimum requis",
    instructionsTitle: "Recharger le portefeuille",
    instructions:
      "Rechargez ce portefeuille (paiement via Stripe Skedisy, comme le portefeuille cliente) pour couvrir la commission Skedisy à chaque réservation. Le paiement carte des clientes arrive à 100 % sur votre Stripe Connect — la commission n'y est pas prélevée.",
    enterAmount: "Montant à recharger",
    quickAmount: "Montants rapides",
    amountPlaceholder: "Saisir le montant",
    amountInvalid: "Veuillez saisir un montant valide.",
    selectPayment: "Mode de paiement",
    momoPhone: "Numéro MTN MoMo",
    momoPhonePlaceholder: "ex. 33612345678",
    momoPhoneHint: "Numéro enregistré sur MTN Mobile Money.",
    noPaymentMethods: "Aucun mode de paiement disponible",
    noPaymentMethodsHint: "Contactez Skedisy pour activer Stripe ou MTN MoMo.",
    recharge: "Recharger",
    gatewayNote: "L'intégration paiement doit être activée par l'administration.",
    paymentSuccess: "Paiement réussi — portefeuille crédité.",
    paymentVerifyFailed: "Échec de vérification du paiement.",
    paymentError: "Erreur lors du traitement du paiement.",
    paymentCancelled: "Paiement annulé. Vous pouvez réessayer.",
    paymentTimeout: "Délai dépassé. Vérifiez votre téléphone ou réessayez.",
    selectPaymentMethod: "Choisissez un mode de paiement.",
    noMethodsEnabled: "Aucun paiement activé — contactez l'admin.",
    enterMomoPhone: "Saisissez votre numéro MTN MoMo.",
    invalidPhone: "Numéro de téléphone invalide.",
    momoSent: "Demande envoyée — validez sur votre téléphone.",
    methodNotSupported: "Mode de paiement non pris en charge.",
    balanceLow:
      "Solde insuffisant pour accepter de nouvelles réservations.",
    balanceBelowMin:
      "Votre solde est sous le minimum requis.",
    needAddAmount: "Ajoutez au moins",
    toAcceptBookings: "pour accepter des réservations.",
    balanceRule:
      "Le solde doit couvrir le minimum + les frais de commission pour les nouvelles réservations.",
    rechargeBody1:
      "Recharge via Stripe Skedisy (portefeuille commission). Choisissez un montant — le solde est crédité ici après validation.",
    rechargeBody2:
      "Consultez l'historique dans « Historique portefeuille » (recharges, commissions, remboursements).",
    amountErrorLabel: "Montant invalide",
    noteFooter:
      "Après paiement réussi, le montant est crédité automatiquement. Historique dans « Historique portefeuille ».",
  },
  dialog: {
    cancelBooking: "Annuler la réservation",
    completeBooking: "Terminer la réservation",
    reason: "Motif",
    reasonRequired: "Le motif est requis.",
    priceAboveMrp: "Le prix ne peut pas dépasser le prix public.",
    bookingInfo: "Détail réservation",
    complainInfo: "Détail réclamation",
    serviceDialog: "Prestation",
    categoryDialog: "Catégorie",
    attributeDialog: "Attribut",
    productDialog: "Produit",
    holidayDialog: "Congé",
    salonTimeDialog: "Horaires salon",
    enterPrice: "Saisir le prix",
    enterName: "Nom",
    enterDetail: "Détail",
    nameRequired: "Le nom est requis.",
    detailsRequired: "Le détail est requis.",
    selectServices: "Choisir les prestations",
    selectSalon: "Choisir le salon",
    selectCategory: "Choisir la catégorie",
    selectCategoryHint: "Sélectionnez une catégorie",
    selectAttribute: "Choisir un attribut",
    selectImages: "Photos (plusieurs)",
    enterDuration: "Durée (minutes)",
    firstNameRequired: "Le prénom est requis.",
    lastNameRequired: "Le nom est requis.",
    mobileRequired: "Le téléphone est requis.",
    mobileInvalid: "Le numéro doit comporter 6 à 13 chiffres.",
    genderRequired: "Le genre est requis.",
    emailRequired: "L'email est requis.",
    emailInvalid: "Adresse email invalide.",
    imageRequired: "La photo est requise.",
    ageRequired: "L'âge est requis.",
    ageInvalid: "Âge invalide (18–100).",
    commissionRequired: "La commission est requise.",
    commissionInvalid: "Commission invalide (0–99 %).",
    passwordRequired: "Le mot de passe est requis.",
    servicePickRequired: "Sélectionnez au moins une prestation.",
    titleRequired: "Le titre est requis.",
    messageRequired: "Le message est requis.",
    durationInvalid: "Durée invalide.",
    priceInvalid: "Prix invalide.",
    priceRequired: "Le prix est requis.",
    checkInTime: "Heure d'arrivée",
    checkOutTime: "Heure de fin",
    productCodeRequired: "Le code produit est requis.",
    productNameRequired: "Le nom du produit est requis.",
    descriptionRequired: "La description est requise.",
    brandRequired: "La marque est requise.",
    categoryRequired: "La catégorie est requise.",
    attributeRequired: "Au moins un attribut est requis.",
    mrpRequired: "Le prix public est requis.",
    shippingRequired: "Les frais de livraison sont requis.",
    mainImageRequired: "L'image principale est requise.",
    imagesRequired: "Au moins une image est requise.",
    imageRequiredCategory: "L'image est requise.",
    openTimeRequired: "L'heure d'ouverture est requise.",
    closeTimeRequired: "L'heure de fermeture est requise.",
    uploadImage: "Changer la photo",
    editProfile: "Modifier le profil",
    changePassword: "Changer le mot de passe",
    passwordSettings: "Mot de passe",
    oldPasswordRequired: "Le mot de passe actuel est requis.",
    newPasswordRequired: "Le nouveau mot de passe est requis.",
    confirmPasswordRequired: "La confirmation est requise.",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    adminNameRequired: "Le nom est requis.",
    adminEmailRequired: "L'email est requis.",
    dateRequired: "La date est requise.",
    salonRequired: "Le salon est requis.",
    endDateRequired: "La date de fin est requise.",
    bankNameRequired: "Le nom de la banque est requis.",
    accountRequired: "Le numéro de compte est requis.",
    branchRequired: "L'agence est requise.",
    ifscRequired: "Le code banque est requis.",
    upiRequired: "L'identifiant UPI est requis.",
    durationRequired: "La durée est requise.",
  },

  form: {
    productCode: "Code produit (6 chiffres)",
    productName: "Nom du produit",
    description: "Description",
    brand: "Marque",
    price: "Prix",
    mrp: "Prix public (MRP)",
    shippingCharges: "Frais de livraison",
    mainImage: "Photo principale",
    serviceName: "Nom de la prestation",
    serviceCharge: "Tarif prestation",
    serviceDuration: "Durée (min)",
    mobileNumber: "Téléphone",
    email: "Email",
    age: "Âge",
    adminCommissionPct: "Commission plateforme (%)",
    salonCommissionPct: "Commission salon (%)",
    bankName: "Nom de la banque",
    accountNumber: "N° de compte",
    branchName: "Agence",
    branchNameTypo: "Agence",
    ifscCode: "Code banque (IFSC)",
    upiId: "Identifiant UPI",
    password: "Mot de passe",
    male: "Homme",
    female: "Femme",
    image: "Photo",
    firstName: "Prénom",
    lastName: "Nom",
    uniqueId: "Référence",
    gender: "Genre",
    emailId: "Email",
    loginType: "Mode de connexion",
    salonName: "Nom du salon",
    platformFeePct: "Frais plateforme (%)",
    platformFeeTypo: "Frais plateforme (%)",
    shareLink: "Lien de partage",
    latitude: "Latitude",
    longitude: "Longitude",
    address: "Adresse",
    landmark: "Repère",
    landMark: "Repère",
    city: "Ville",
    state: "Région",
    country: "Pays",
    date: "Date",
    time: "Heure",
    checkOutTime: "Heure de fin",
    title: "Titre",
    message: "Message",
    details: "Détail",
    reportDateTime: "Date et heure du signalement",
    solvedDateTime: "Date et heure de résolution",
    expertCount: "Nombre de pros",
    mobile: "Téléphone",
    day: "Jour",
    slotTimeMinute: "Créneau (minutes)",
    deliveredServiceName: "Prestation réalisée",
    trackingId: "N° de suivi",
    trackingLink: "Lien de suivi",
    subTotal: "Sous-total",
    wallet: "Portefeuille",
    name: "Nom",
    about: "À propos",
  },
  bonusPenalty: {
    title: "Bonus ou pénalité",
    bonus: "Bonus",
    penalty: "Pénalité",
    note: "Note",
    hint: "Indiquez un bonus ou une pénalité (pas les deux).",
    required: "Saisissez un bonus ou une pénalité.",
  },
  settings: {
    privacyPolicyRequired: "Le lien politique de confidentialité est requis.",
    tncRequired: "Les CGU sont requises.",
    stripePublishableRequired: "La clé publique Stripe est requise.",
    stripeSecretRequired: "La clé secrète Stripe est requise.",
    razorIdRequired: "L'identifiant Razorpay est requis.",
    razorSecretRequired: "La clé secrète Razorpay est requise.",
    taxRequired: "La taxe est requise.",
    currencyNameRequired: "Le nom de la devise est requis.",
    currencySymbolRequired: "Le symbole devise est requis.",
    flutterWaveRequired: "La clé Flutterwave est requise.",
    firebaseRequired: "La clé Firebase est requise.",
    adminCommissionRequired: "La commission admin (produits) est requise.",
    cancelOrderRequired: "Les frais d'annulation commande sont requis.",
    minWithdrawRequired: "Le montant minimum de retrait est requis.",
    stripePublishablePh: "Clé publique Stripe",
    stripeSecretPh: "Clé secrète Stripe",
    stripeActive: "Paiement Stripe (activer / désactiver)",
    razorSecretPh: "Clé secrète Razorpay",
    razorIdPh: "Identifiant Razorpay",
    razorActive: "Paiement Razorpay",
    flutterWavePh: "Clé Flutterwave",
    flutterActive: "Paiement Flutterwave (activer / désactiver)",
    maintenanceMode: "Mode maintenance",
    privacyPolicyPh: "Lien politique de confidentialité",
    tncPh: "Conditions générales (CGU)",
    taxPh: "Taxe (%)",
    productRequestNew: "Demandes nouveau produit (vendeur)",
    productRequestUpdate: "Mise à jour demandes produit (vendeur)",
    cancelOrderPh: "Frais annulation commande",
    adminCommissionPh: "Commission admin (produits)",
    currencyNamePh: "Nom de la devise",
    currencySymbolPh: "Symbole devise",
    minWithdrawPh: "Retrait minimum",
    paymentSettings: "Paiements",
    generalSettings: "Paramètres généraux",
    adminCommissionLabel: "Commission admin produits (%)",
    invalidJson: "JSON invalide.",
  },
  appointment: {
    title: "Nouveau rendez-vous",
    onDatePrefix: "Le",
    atTime: "À",
    salon: "Salon",
    expert: "Pro",
    customer: "Cliente",
    chooseDate: "Choisir la date",
    chooseTime: "Choisir l'heure",
    selectSalon: "Choisir le salon",
    selectExpert: "Choisir le pro",
    selectCustomer: "Choisir la cliente",
    salonRequired: "Le salon est requis.",
    expertRequired: "Le pro est requis.",
    customerRequired: "La cliente est requise.",
    clientSince: "Cliente depuis",
    email: "Email",
    uniqueId: "Référence",
    close: "Fermer",
  },
  common: {
    enterYour: "Saisir",
    submit: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    update: "Mettre à jour",
    back: "Retour",
    searchPlaceholder: "Rechercher…",
    paginationShow: "Afficher",
    confirm: "Confirmer",
    accept: "Accepter",
    all: "Tout",
    pending: "En attente",
    approved: "Validé",
    rejected: "Refusé",
  },
  alert: {
    title: "Confirmer l'action ?",
    text: "Cette action est définitive.",
    logout: "Se déconnecter",
  },
  toast: {
    success: "Succès",
    error: "Erreur",
    warning: "Attention",
    info: "Info",
    oops: "Oups",
    notice: "Notification",
    missingFile: "Vérifiez les champs requis — fichier manquant.",
    loginOk: "Connexion réussie.",
    loginFail: "Échec de connexion — réessayez.",
    adminUpdated: "Profil salon mis à jour.",
    passwordUpdated: "Mot de passe mis à jour.",
    expertCreated: "Pro ajouté.",
    expertUpdated: "Pro mis à jour.",
    expertDeleted: "Pro supprimé.",
    serviceAdded: "Prestation ajoutée.",
    serviceDeleted: "Prestation supprimée.",
    categoryAdded: "Catégorie ajoutée.",
    categoryUpdated: "Catégorie mise à jour.",
    categoryDeleted: "Catégorie supprimée.",
    categoryStatus: "Statut catégorie mis à jour.",
    bookingCancelled: "Réservation annulée.",
    holidayAdded: "Congé ajouté.",
    holidayDeleted: "Congé supprimé.",
    timeUpdated: "Horaires mis à jour.",
    breakUpdated: "Pause salon mise à jour.",
    reviewDeleted: "Avis supprimé.",
    attendanceUpdated: "Présence mise à jour.",
    notificationSent: "Notification envoyée.",
    updated: "Mis à jour.",
    salaryPaid: "Paiement enregistré.",
    bonusUpdated: "Bonus / pénalité mis à jour.",
    expertPaid: "Paiement pro enregistré.",
    salonCreated: "Salon créé.",
    salonUpdated: "Salon mis à jour.",
    salonDeleted: "Salon supprimé.",
    cityAdded: "Ville ajoutée.",
    cityBlocked: "Ville bloquée.",
    taxAdded: "Taxe ajoutée.",
    taxUpdated: "Taxe mise à jour.",
    taxStatus: "Statut taxe mis à jour.",
    productCategoryAdded: "Catégorie produit ajoutée.",
    citiesUpdated: "Villes mises à jour.",
  },
  pages: {
    experts: "Équipe",
    addExpert: "Ajouter un·e pro",
    reviews: "Avis",
    complaints: "Réclamations",
    bookings: "Réservations",
    todayPending: "Réservations en attente (aujourd'hui)",
    daywiseBookings: "Réservations par jour",
    monthlyReport: "Rapport mensuel",
    services: "Prestations",
    products: "Produits",
    addProduct: "Ajouter un produit",
    orders: "Commandes",
    product: "Produit",
    productCategory: "Catégorie produit",
    attribute: "Attribut",
    salonTime: "Horaires",
    holiday: "Congés",
    staffAttendance: "Présences équipe",
    staffAttendanceData: "Détail des présences",
    teamCalendar: "Planning équipe",
    expertEarnings: "Gains des pros",
    salonEarnings: "Revenus salon",
    salonPayment: "Paiements salon",
    withdrawMoney: "Retrait",
    wallet: "Portefeuille",
    walletHistory: "Historique portefeuille",
    profile: "Profil salon",
  },
  salonForm: {
    addTitle: "Ajouter un salon",
    editTitle: "Modifier le salon",
    name: "Nom du salon",
    email: "Email",
    mobile: "Téléphone",
    password: "Mot de passe",
    platformFee: "Frais plateforme (%)",
    address: "Adresse",
    landmark: "Repère",
    city: "Ville",
    state: "Région",
    country: "Pays",
    latitude: "Latitude",
    longitude: "Longitude",
    about: "À propos (fiche publique)",
    mainImage: "Photo principale",
    gallery: "Photos du salon (max. 10)",
    nameRequired: "Le nom est requis.",
    aboutRequired: "La description est requise.",
    emailRequired: "L'email est requis.",
    passwordRequired: "Le mot de passe est requis.",
    platformFeeRequired: "Les frais plateforme sont requis.",
    mobileRequired: "Le téléphone est requis.",
    addressRequired: "L'adresse est requise.",
    landmarkRequired: "Le repère est requis.",
    cityRequired: "La ville est requise.",
    stateRequired: "La région est requise.",
    countryRequired: "Le pays est requis.",
    latitudeRequired: "La latitude est requise.",
    longitudeRequired: "La longitude est requise.",
    imagesRequired: "Au moins une photo est requise.",
    imagesMax: "Maximum 10 photos.",
  },
  apiMessages: {
    genericError: "Une erreur est survenue.",
    unexpectedError: "Erreur inattendue.",
    invalidCredentials: "Identifiants incorrects.",
    unauthorized: "Session expirée — reconnectez-vous.",
    userNotFound: "Utilisateur introuvable.",
    salonNotFound: "Salon introuvable.",
    expertNotFound: "Pro introuvable.",
    bookingNotFound: "Réservation introuvable.",
    notFoundGeneric: "Élément introuvable.",
    requiredGeneric: "Champs requis manquants.",
    invalidGeneric: "Données invalides.",
    successGeneric: "Opération réussie.",
    insufficientBalance: "Solde insuffisant.",
    withdrawSubmitted: "Demande de retrait envoyée.",
  },
  paymentFields: {
    "upi id": "Identifiant UPI",
    upi: "UPI",
    "ifsc code": "Code IFSC",
    ifsc: "Code IFSC",
    "bank name": "Nom de la banque",
    "account number": "N° de compte",
    "branch name": "Agence",
    "mobile number": "Téléphone",
    email: "Email",
    paypal: "PayPal",
    "pay pal": "PayPal",
    "account holder name": "Titulaire du compte",
    "holder name": "Titulaire du compte",
  },
  paymentMethods: {
    "bank transfer": "Virement bancaire",
    bank: "Banque",
    upi: "UPI",
    paypal: "PayPal",
    razorpay: "Razorpay",
    stripe: "Stripe",
    "mtn momo": "MTN MoMo",
    cash: "Espèces",
  },
  withdraw: {
    title: "Demande de retrait",
    balanceLabel: "Solde disponible",
    amountLabel: "Montant à retirer",
    amountPlaceholder: "Saisir le montant",
    amountMinError: "Le montant doit être au moins",
    amountMaxNote: "Montant minimum de retrait :",
    paymentOption: "Mode de paiement",
    paymentField: "Saisir :",
    paymentFieldPlaceholder: "Votre",
    instructionsTitle: "Comment retirer",
    instructions:
      "Saisissez le montant (minimum indiqué ci-dessus), choisissez votre mode de paiement et renseignez les coordonnées. La demande est traitée par l'équipe Skedisy — vérifiez que vos informations sont à jour.",
    amountRequired: "Saisissez un montant.",
    selectPaymentDetail: "Renseignez au moins un détail de paiement.",
    submit: "Demander le retrait",
    bannerAlt: "Retrait des gains",
  },
  labels: {
    bookingType: "Type de réservation",
    selectDate: "Choisir une date",
    selectMonth: "Choisir un mois",
    paymentDate: "Date de paiement",
    addNew: "Ajouter",
    addCategory: "Ajouter une catégorie",
    addProductCategory: "Ajouter une catégorie produit",
    category: "Catégories",
    products: "Produits",
    addProducts: "Ajouter un produit",
    productCategory: "Catégorie produit",
    newHoliday: "Nouveau congé",
    todayPendingTitle: "Réservations en attente (aujourd'hui)",
    yearlyPayment: "Historique paiements par année",
    salonPayment: "Paiements salon",
    salonEarnings: "Revenus salon",
    salonOrders: "Commandes salon",
    walletHistory: "Historique portefeuille",
    expertEarningsDetail: "Détail gains pro",
    staffAttendanceData: "Détail des présences",
    selectMonthLabel: "Mois",
    bookingFeeDeduction: "Frais de réservation déduits",
    bookingComplete: "Réservation terminée",
    withdrawPending: "Retrait en attente",
    withdrawApproved: "Retrait validé",
    withdrawDeclined: "Retrait refusé",
    editOrder: "Modifier la commande",
    selectStatus: "Choisir le statut",
    cancelOrderChargesNote: "Frais d'annulation :",
    cannotCancelOrder: "Annulation impossible : le sous-total est inférieur aux frais d'annulation.",
    priceRequired: "Le prix est requis.",
    imagePathRequired: "Le chemin image est requis.",
    imageRequired: "L'image est requise.",
    openTimeRequired: "L'heure d'ouverture est requise.",
    dayRequired: "Le jour est requis.",
    closeTimeRequired: "L'heure de fermeture est requise.",
    dayRequiredBang: "Le jour est requis.",
    slotTimeRequired: "Le créneau est requis.",
    minWithdrawLabel: "Montant minimum de demande de retrait",
    cancelOrderChargesPct: "Frais annulation commande (%)",
    stripeSecretLabel: "Clé secrète Stripe",
    newItems: "Nouveaux articles",
    updatedItems: "Articles mis à jour",
    updateBtn: "Mettre à jour",
    salonBookingsTitle: "Réservations du salon",
    expertsTitle: "Coiffeur·se·s / pros",
    servicesTitle: "Prestations",
    salonTimeTitle: "Horaires salon",
    withdrawMoneyTitle: "Retrait",
    salonWithdrawRequest: "Demandes de retrait salon",
    expertWithdrawRequest: "Demandes de retrait pro",
    productCategoryDialog: "Catégorie produit",
    paymentHistoryTitle: "Historique des paiements",
    bookingsTitle: "Réservations",
    minAmountApply: "Montant minimum",
  },

};
