/** Aligné AUTHENTICITE_SKEDISY — portail salon (salonpanel). */
export const SKEDISY_SALON_PORTAL_COPY = {
  kicker: "Skedisy",
  welcome: "Espace salon",
  loginTitle: "Connexion",
  loginSubtitle: "Accédez à votre espace professionnel.",
  loginHint: "",
  signUpTitle: "Créer l'accès",
  signUpSubtitle: "Code d'invitation requis pour activer votre salon.",
  signUpHint: "Email, mot de passe et code fourni par Skedisy.",
  submitLogin: "Se connecter",
  submitSignUp: "Créer le compte",
  email: "Email",
  password: "Mot de passe",
  confirmPassword: "Confirmer le mot de passe",
  code: "Code d'invitation",
  errEmail: "L'email est requis.",
  errPassword: "Le mot de passe est requis.",
  errConfirmPassword: "La confirmation est requise.",
  errPasswordMismatch: "Les mots de passe ne correspondent pas.",
  errCode: "Le code est requis.",
  footerLink: "Découvrir skedisy.com",
  footerPro: "Réclamer ma fiche salon",
  profileValueTitlePlaceholder:
    "ex. Salon afro en IDF — tresses, locks, perruques",
  profileValueDescPlaceholder:
    "Ce qui rend votre salon unique (prestations afro, quartier, expertise…)",
  profileHeroHint:
    "Image en tête de votre fiche publique (clientes : skedisy.com · réservation sur l'app).",
  profileGalleryLabel: "Photos réalisations (mosaïque fiche publique)",
  profileGalleryHint:
    "Jusqu’à 10 photos affichées en mosaïque sur votre page salon (comme StyleSeat). Formats JPG/PNG.",
  profileCancelPolicyLabel: "Politique No-Show / annulation tardive",
  profileCancelPolicyHint:
    "Fenêtre gratuite (défaut 24 h) puis, si activé, rétention de l’acompte (ex. 50 %) sur annulation tardive. Reprogrammation libre uniquement dans la fenêtre gratuite.",
  profileCancelPolicyEnabled: "Activer la politique sur la fiche",
  profileCancelFreeHours: "Annulation gratuite jusqu’à (heures avant RDV)",
  profileCancelLatePercent: "Pénalité annulation tardive (%)",
  profileCancelNoShowPercent: "Pénalité no-show (%)",
  profileLoyaltyLabel: "Fidélité rebooking (même prestation)",
  profileLoyaltyHint:
    "Si une cliente rebook la même presta chez vous, elle obtient une réduction. Basé sur l’historique completed — pas de points génériques.",
  profileLoyaltyEnabled: "Activer la réduction fidélité",
  profileLoyaltyPercent: "Réduction (%)",
  profileLoyaltyMinVisits: "Après combien de visites completed ?",
  profileLoyaltyMinVisitsHint: "1 = dès le 2ᵉ passage sur la même presta",
  profileLoyaltyMax: "Plafond réduction (€, 0 = pas de plafond)",
  profileValueTitleLabel: "Accroche fiche publique",
  profileValueDescLabel: "Description",
  profileValueFeaturesLabel: "Points forts (séparés par des virgules)",
  profileValueFeaturesPlaceholder:
    "ex. Tresses sans tension, locks, perruques, homme, esthétique",
  profileValueFeaturesHint:
    "Affichés sur skedisy.com — prestations afro nommées, pas de formules génériques.",
  updateCodeTitle: "Mettre à jour le code",
  updateCodeSubtitle: "Nouveau code d'invitation pour votre compte salon.",
  updateCodeHint: "Email, mot de passe actuel et nouveau code.",
  submitUpdateCode: "Enregistrer",
  nameRequired: "Le nom est requis.",
  imageRequired: "La photo est requise.",
  oldPasswordRequired: "Le mot de passe actuel est requis.",
  newPasswordRequired: "Le nouveau mot de passe est requis.",
  confirmPasswordRequired: "La confirmation est requise.",
  profileSalonFallback: "Salon",
  profileTitleSuffix: " — Profil",
  autoConfirmBookingsLabel: "Confirmation automatique des réservations",
  autoConfirmBookingsHint:
    "Les réservations clientes sont confirmées immédiatement (comme Planity). L'expert n'a pas à les accepter. Désactivez uniquement si vous validez manuellement depuis ce panel.",
  paymentSettingsTitle: "Modes de paiement clientes",
  paymentSettingsPageTitle: "Paiements & Stripe Connect",
  paymentSettingsPageIntro:
    "Espèces et/ou carte pour vos clientes. La carte est encaissée à 100 % sur votre Stripe Connect. La commission Skedisy est prélevée sur votre portefeuille salon (page Portefeuille), pas sur le paiement cliente.",
  paymentCashLabel: "Paiement en espèces (sur place)",
  paymentCashHint: "Le client paie au salon après la prestation.",
  paymentStripeLabel: "Paiement en ligne (Stripe)",
  paymentStripeHint:
    "La cliente paie 100 % sur votre compte Stripe Connect. Aucune commission n'est déduite de ce paiement.",
  paymentAdminStripeNote:
    "Commission Skedisy : prélevée sur le portefeuille salon (rechargez-le via Stripe Skedisy sur la page Portefeuille — même principe que le portefeuille cliente).",
  stripeConnectTitle: "Compte Stripe Connect",
  stripeConnectReady: "Compte actif — paiements carte acceptés",
  stripeConnectPending: "Configuration incomplète",
  stripeConnectDisabled: "Stripe non connecté",
  stripeConnectButton: "Configurer / mettre à jour Stripe",
  stripeConnectPlatformOff: "Stripe Connect n'est pas activé par Skedisy. Contactez le support.",
  stripeConnectStep1: "1. Activez « Paiement en ligne (Stripe) » ci-dessus",
  stripeConnectStep2: "2. Cliquez sur le bouton pour compléter votre dossier Stripe",
  stripeConnectStep3: "3. Une fois validé, vos clientes pourront payer par carte dans l'app",
  stripeConnectChargesOff: "Paiements carte en attente de validation Stripe",
  stripeConnectPayoutsOff: "Virements bancaires en attente de validation Stripe",
  mobileLabel: "Téléphone",
  mobileRequired: "Le téléphone est requis.",
  latitudeLabel: "Latitude",
  latitudeRequired: "La latitude est requise.",
  longitudeLabel: "Longitude",
  longitudeRequired: "La longitude est requise.",
  aboutLabel: "À propos",
  aboutRequired: "La description est requise.",
  aboutPhoneHint:
    "Vous pouvez y indiquer votre numéro d’appel si vous souhaitez être joint par téléphone.",
  socialSectionTitle: "Réseaux sociaux (fiche publique)",
  socialSectionHint:
    "Les logos Instagram, Facebook et TikTok apparaîtront à côté de Message sur votre fiche salon.",
  instagramLabel: "Page Instagram",
  instagramHint: "URL ou @pseudo — logo Instagram sur votre fiche publique.",
  facebookLabel: "Page Facebook",
  facebookHint: "URL ou nom de page — logo Facebook sur votre fiche publique.",
  tiktokLabel: "Compte TikTok",
  tiktokHint: "URL ou @pseudo — logo TikTok sur votre fiche publique.",
  messagingEnabledLabel: "Messagerie Skedisy",
  messagingEnabledHint:
    "Les clientes peuvent vous écrire depuis votre fiche (photos d'inspiration comprises). Répondez dans Messages.",
  addressLabel: "Adresse",
  addressRequired: "L'adresse est requise.",
  landmarkLabel: "Repère",
  landmarkRequired: "Le repère est requis.",
  cityLabel: "Ville",
  cityRequired: "La ville est requise.",
  stateLabel: "Région",
  stateRequired: "La région est requise.",
  countryLabel: "Pays",
  countryRequired: "Le pays est requis.",
  oldPassword: "Mot de passe actuel",
  newPassword: "Nouveau mot de passe",
  confirmPasswordField: "Confirmer le mot de passe",
};
