/** Aligné AUTHENTICITE_SKEDISY — portail salon (salonpanel). */
export const SKEDISY_SALON_PORTAL_COPY = {
  kicker: "Île-de-France · Beauté afro",
  welcome: "Espace salon Skedisy",
  loginTitle: "Connexion",
  loginSubtitle:
    "Agenda et prestations nommées (tresses, locks, perruques, homme, esthétique) — pensé pour les salons afro en IDF.",
  loginHint: "Email et mot de passe de votre compte salon.",
  signUpTitle: "Créer l'accès",
  signUpSubtitle: "Code d'invitation requis pour activer votre salon.",
  signUpHint: "Email, mot de passe et code fourni par Skedisy.",
  submitLogin: "Se connecter",
  submitSignUp: "Créer le compte",
  email: "Email",
  password: "Mot de passe",
  confirmPassword: "Confirmer le mot de passe",
  code: "Code d'invitation",
  errEmail: "L'email est requis.",
  errPassword: "Le mot de passe est requis.",
  errConfirmPassword: "La confirmation est requise.",
  errPasswordMismatch: "Les mots de passe ne correspondent pas.",
  errCode: "Le code est requis.",
  footerLink: "Découvrir skedisy.com",
  footerPro: "Réclamer ma fiche salon",
  profileValueTitlePlaceholder:
    "ex. Salon afro en IDF — tresses, locks, perruques",
  profileValueDescPlaceholder:
    "Ce qui rend votre salon unique (prestations afro, quartier, expertise…)",
  profileHeroHint:
    "Image en tête de votre fiche publique (clientes : skedisy.com · réservation sur l'app).",
  profileValueTitleLabel: "Accroche fiche publique",
  profileValueDescLabel: "Description",
  profileValueFeaturesLabel: "Points forts (séparés par des virgules)",
  profileValueFeaturesPlaceholder:
    "ex. Tresses sans tension, locks, perruques, homme, esthétique",
  profileValueFeaturesHint:
    "Affichés sur skedisy.com — prestations afro nommées, pas de formules génériques.",
  updateCodeTitle: "Mettre à jour le code",
  updateCodeSubtitle: "Nouveau code d'invitation pour votre compte salon.",
  updateCodeHint: "Email, mot de passe actuel et nouveau code.",
  submitUpdateCode: "Enregistrer",
  nameRequired: "Le nom est requis.",
  imageRequired: "La photo est requise.",
  oldPasswordRequired: "Le mot de passe actuel est requis.",
  newPasswordRequired: "Le nouveau mot de passe est requis.",
  confirmPasswordRequired: "La confirmation est requise.",
  profileSalonFallback: "Salon",
  profileTitleSuffix: " — Profil",
  mobileLabel: "Téléphone",
  mobileRequired: "Le téléphone est requis.",
  latitudeLabel: "Latitude",
  latitudeRequired: "La latitude est requise.",
  longitudeLabel: "Longitude",
  longitudeRequired: "La longitude est requise.",
  aboutLabel: "À propos",
  aboutRequired: "La description est requise.",
  addressLabel: "Adresse",
  addressRequired: "L'adresse est requise.",
  landmarkLabel: "Repère",
  landmarkRequired: "Le repère est requis.",
  cityLabel: "Ville",
  cityRequired: "La ville est requise.",
  stateLabel: "Région",
  stateRequired: "La région est requise.",
  countryLabel: "Pays",
  countryRequired: "Le pays est requis.",
  oldPassword: "Mot de passe actuel",
  newPassword: "Nouveau mot de passe",
  confirmPasswordField: "Confirmer le mot de passe",
};
