// Language Translation System for Skedisy.com
const translations = {
    en: {
        // Navigation
        'nav.aiConcierge': 'AI Concierge',
        'nav.documentation': 'Documentation',
        'nav.menu': 'Menu',
        'nav.login': 'Login',
        
        // Hero Section
        'hero.title': 'The #1 Platform to Manage Your Salon',
        'hero.subtitle': '<strong>50,000+ salons</strong> trust our beauty industry reference, used by <strong>10M+ users</strong> every month.',
        'hero.addSalon': 'Add My Salon',
        'hero.tryAI': 'Try AI Concierge',
        'hero.trustBadge': '4.8/5 on Trustpilot',
        'hero.bookingManagement': 'Booking management',
        'hero.simplifiedPayments': 'Simplified payments',
        'hero.noCommitment': 'No commitment',
        
        // Request Buttons
        'request.salonTitle': 'Would you like to integrate your salon on Skedisy platform?',
        'request.salonButton': 'Make your Request',
        'request.customerTitle': 'Would you like to book services from a salon?',
        'request.customerButton': 'Book here',
        
        // Stats
        'stats.professionals': 'Professionals',
        'stats.appointments': 'Appointments managed monthly',
        'stats.onlineBookings': 'Online bookings outside business hours',
        
        // Features
        'features.bookTitle': 'Book Your Appointment Online',
        'features.bookDesc': 'Find your favorite salon and book your beauty appointment 24/7, instantly and easily. No more waiting on the phone—just a few clicks and your spot is reserved!',
        'features.manageTitle': 'Manage Your Salon Effortlessly',
        'features.manageDesc': 'Salon owners can manage bookings, staff, and schedules from anywhere. Simplify your daily operations and focus on what matters most: your clients.',
        
        // New Clients
        'clients.title': 'New Clients.<br>Continuously.',
        'clients.desc': 'Some are looking for exactly your specialty. Some are new to the neighborhood. Some have decided to take care of themselves. Let them find their rare pearl: you.',
        'clients.showcase': 'Showcase page for your establishment',
        'clients.reviews': 'Certified client reviews',
        'clients.ranking': 'Optimized Google ranking',
        'clients.discover': 'Discover for Free',
        
        // Professional Stats
        'proStats.title': 'Are you a beauty professional?<br>Discover online appointment booking!',
        'proStats.increase': 'increase in frequency for online bookings',
        'proStats.noShows': 'fewer no-shows with SMS appointment reminders',
        'proStats.outsideHours': 'of online bookings made outside business hours',
        'proStats.salons': 'Salons & institutes',
        'proStats.booked': 'Booked every second',
        'proStats.sold': 'in appointments sold',
        
        // Platform Features
        'platform.manage': 'Manage',
        'platform.manageDesc': 'Control every aspect of your business: bookings, sales, clients, locations, and team members. Analyze your business with detailed reports and statistics.',
        'platform.grow': 'Grow',
        'platform.growDesc': 'Attract new clients on the world\'s largest beauty & wellness marketplace and keep them coming back with built-in marketing tools.',
        'platform.getPaid': 'Get Paid',
        'platform.getPaidDesc': 'Get paid quickly and securely with integrated payments, reduce no-shows with deposits, and simplify your checkout process.',
        'platform.aiTitle': 'AI Beauty Concierge',
        'platform.aiDesc': 'Get personalized beauty recommendations powered by AI. Upload your selfie and discover the perfect services for you.',
        'platform.tryNow': 'Try Now →',
        
        // CTA
        'cta.ready': 'Ready to grow your business?',
        'cta.join': 'Join thousands of professionals who trust SalonPortal to manage and grow their business. Start for free today!',
        'cta.getStarted': 'Get Started',
        'cta.million': '10,000,000',
        'cta.millionDesc': '10 million people book a beauty appointment every month on SalonPortal. Take care of them.',
        'cta.final': 'More than 50,000 professionals have transformed their days with SalonPortal. Join them.',
        
        // FAQ
        'faq.title': 'Frequently Asked Questions',
        'faq.customerAccount': 'How to create a customer account on Skedisy?',
        'faq.salonAccount': 'How to create a salon owner account?',
        'faq.expertCredentials': 'How does an expert get their credentials?',
        'faq.downloadApp': 'How to download the app?',
        'faq.appDifference': 'What is the difference between the Customer and Expert app?',
        'faq.bookService': 'How does a customer book a service from a salon on the customer app?',
        'faq.acceptReservation': 'How can an expert accept or refuse a reservation on the expert app?',
        'faq.manageBusiness': 'How can a salon owner add a new expert, add services, and manage their business on the business owner platform?',
        'faq.newClients': 'Will SalonPortal bring me new clients?',
        'faq.newClientsDesc': 'Your salon will be visible to our 10 million monthly users and listed on search networks like Google to easily find your establishment. Verified reviews from your previous appointments will encourage visitors to book simply, without fees.',
        
        // Footer
        'footer.tagline': 'Transform your salon management with our all-in-one solution.',
        'footer.about': 'About',
        'footer.myAccount': 'My Skedisy Account',
        'footer.signUp': 'Sign Up',
        'footer.pricing': 'Pricing',
        'footer.helpCenter': 'Help Center',
        'footer.solutions': 'Our Solutions',
        'footer.onlineBooking': '24/7 Online Booking',
        'footer.calendar': 'Calendar Management',
        'footer.pos': 'Certified POS',
        'footer.payment': 'Payment Terminal',
        'footer.workTime': 'Work Time Management',
        'footer.marketing': 'Marketing Solutions',
        'footer.legal': 'Legal',
        'footer.terms': 'Terms of Service',
        'footer.privacy': 'Privacy Policy',
        'footer.cookies': 'Cookie Management',
        'footer.rights': '© 2024 Skedisy. All rights reserved.',
        
        // Modal
        'modal.choosePlatform': 'Choose Your Platform',
        'modal.selectDevice': 'Select your device to download the app',
        'modal.android': 'Android',
        'modal.downloadAndroid': 'Download from Google Play Store',
        'modal.download': 'Download',
        'modal.iphone': 'iPhone',
        'modal.downloadIOS': 'Download from App Store',
        'modal.requestDemo': 'Request a Demo',
        'modal.sendRequest': 'Send your request to:',
        'modal.includeInfo': 'Please include the following information in your email:',
        'modal.managerName': 'Manager Name',
        'modal.phoneNumber': 'Phone Number',
        'modal.emailAddress': 'Email Address',
        'modal.establishmentType': 'Type of Establishment?',
        
        // QR Code
        'qr.customerApp': 'Download Customer App',
        'qr.expertApp': 'Download the Expert App',
        
        // Language Switcher
        'lang.english': 'English',
        'lang.french': 'Français',
        'lang.switchTo': 'Switch to',
        
        // Documentation
        'doc.documentation': 'Documentation',
        'doc.customerApp': 'Customer App',
        'doc.expertApp': 'Expert App',
        'doc.salonOwnerPortal': 'Salon Owner Portal',
        'doc.gettingStarted': 'Getting Started',
        'doc.homeScreen': 'Home Screen',
        'doc.bookingProcess': 'Booking Process',
        'doc.bookingScreen': 'Booking Screen',
        'doc.productCategory': 'Product Category',
        'doc.notifications': 'Notifications',
        'doc.profile': 'Profile',
        'doc.wallet': 'Wallet',
        'doc.myRevenue': 'My Revenue',
        'doc.reservationDetails': 'Reservation Details',
        'doc.slotManagement': 'Slot Management',
        'doc.orderDetails': 'Order Details',
        'doc.expertProfile': 'Expert Profile',
        'doc.dashboard': 'Dashboard',
        'doc.expertsManagement': 'Experts Management',
        'doc.reviews': 'Reviews',
        'doc.complaints': 'Complaints',
        'doc.expertAttendance': 'Expert Attendance',
        'doc.orders': 'Orders',
        'doc.services': 'Services',
        'doc.products': 'Products',
        'doc.attributes': 'Attributes',
        'doc.salonTime': 'Salon Time',
        'doc.salonHoliday': 'Salon Holiday',
        'doc.walletHistory': 'Wallet History',
        'doc.withdrawMoney': 'Withdraw Money',
        'doc.customerAppWelcome': 'Welcome to the Skedisy Customer App documentation. This comprehensive guide will walk you through every feature and functionality of the customer application, helping you make the most of your booking experience.',
        'doc.tableOfContentsCustomer': 'Table of Contents - Customer App',
        'doc.lookingForExpertApp': 'Looking for Expert App documentation?',
        'doc.clickHere': 'Click here',
        'doc.note': 'Note:',
        'doc.customerAppNote': 'The Skedisy Customer App is designed with a mobile-first approach, providing an intuitive and seamless experience for booking salon services, managing appointments, and accessing your account information.',
        'doc.homeScreenDesc': 'The Home Screen is your main entry point to the Skedisy app. It provides quick access to service categories, nearby salons, and search functionality.',
        'doc.expertAppWelcome': 'Welcome to the Skedisy Expert App documentation. This comprehensive guide will help you understand and utilize all features of the expert application, designed to help service providers manage their bookings, revenue, schedules, and customer interactions efficiently.',
        'doc.salonOwnerPortalWelcome': 'Welcome to the Skedisy Salon Owner Portal documentation. This comprehensive guide will help you understand and utilize all features of the web-based administrative dashboard, designed to help salon owners manage their business operations, staff, services, finances, and customer interactions efficiently.',
        
        // Documentation - Common Sections
        'doc.headerSection': 'Header Section',
        'doc.categorySection': 'Category Section',
        'doc.nearbySalonsSection': 'Nearby Salons Section',
        'doc.bottomNavigation': 'Bottom Navigation',
        'doc.brandNameLocation': 'Brand Name & Location',
        'doc.actionIcons': 'Action Icons',
        'doc.searchBar': 'Search Bar',
        'doc.viewingSalonDetails': 'Viewing Salon Details',
        'doc.bookingSteps': 'Booking Steps',
        'doc.bookingProcessOverview': 'Booking Process Overview',
        'doc.twoWaysToStart': 'Two Ways to Start Booking',
        'doc.bookThroughExpert': 'Book Through Expert',
        'doc.bookThroughSalon': 'Book Through Salon',
        'doc.selectSalon': 'Select Salon',
        'doc.chooseServiceVenue': 'Choose Service Venue',
        'doc.selectExpert': 'Select Expert',
        'doc.chooseDateTime': 'Choose Date & Time',
        'doc.selectPaymentMethod': 'Select Payment Method',
        'doc.confirmBooking': 'Confirm Booking',
        'doc.salonListings': 'Salon Listings',
        'doc.salonDetailPage': 'Salon Detail Page',
        'doc.selectingService': 'Selecting a Service',
        'doc.venueSelection': 'Venue Selection',
        'doc.expertSelection': 'Expert Selection',
        'doc.expertDetails': 'Expert Details',
        'doc.dateTimeSelection': 'Date and Time Selection',
        'doc.paymentMethod': 'Payment Method',
        'doc.bookingConfirmation': 'Booking Confirmation',
        'doc.completeServiceOfferings': 'Complete service offerings',
        'doc.availableTimeSlots': 'Available time slots',
        'doc.expertProfiles': 'Expert profiles',
        'doc.pricingInformation': 'Pricing information',
        'doc.customerReviews': 'Customer reviews',
        'doc.heartIcon': 'Heart Icon',
        'doc.shoppingBagIcon': 'Shopping Bag Icon',
        'doc.accessFavorites': 'Access your favorites and saved salons',
        'doc.viewCart': 'View your cart or current bookings',
        'doc.findServices': 'The prominent search bar allows you to quickly find services by typing keywords. Simply tap the search bar and enter what you\'re looking for (e.g., "haircut", "manicure", "facial").',
        'doc.categoryList': 'Below the search bar, you\'ll find a horizontal scrollable list of service categories. Each category is represented by:',
        'doc.iconLabel': 'Icon: Visual representation of the service type',
        'doc.categoryName': 'Label: Category name (e.g., "Body Care", "Makeup Services", "Nail Care", "Hair Services", "Skin & Facial")',
        'doc.tapCategory': 'Tap on any category to view available services in that category. You can also tap "View All" to see all categories at once.',
        'doc.nearbySalonsDesc': 'The "Nearby Salons" section displays salons in your area, sorted by proximity. Each salon card shows:',
        'doc.salonImage': 'Salon Image: Visual preview of the salon interior',
        'doc.salonName': 'Salon Name: The business name',
        'doc.rating': 'Rating: Star rating and review score',
        'doc.location': 'Location: Full address with map pin icon',
        'doc.distance': 'Distance: Distance from your current location in kilometers',
        'doc.status': 'Status: Open/Closed indicator with color-coded button',
        'doc.favoriteIcon': 'Favorite Icon: Heart icon to save the salon to your favorites',
        'doc.tapSalonCard': 'Tap on any salon card to view detailed information, including:',
        'doc.bottomNavDesc': 'The bottom navigation bar provides quick access to the main sections of the app:',
        'doc.homeIcon': 'Home (House Icon): Return to the home screen',
        'doc.calendar': 'Calendar: View your appointments and bookings',
        'doc.shoppingBag': 'Shopping Bag: Access your cart and bookings',
        'doc.bell': 'Bell: View notifications',
        'doc.profile': 'Profile: Access your account settings and wallet',
        'doc.topLeftDisplays': 'The top left displays the "Skedisy" brand name with your location indicator (e.g., "Nb" for your current area).',
        'doc.topRightIcons': 'On the top right, you\'ll find two outline icons:',
        'doc.option1': 'Option 1',
        'doc.option2': 'Option 2',
        'doc.step1': 'Step 1',
        'doc.step2': 'Step 2',
        'doc.step3': 'Step 3',
        'doc.step4': 'Step 4',
        'doc.step5': 'Step 5',
        'doc.step6': 'Step 6',
        'doc.bookingProcessDesc': 'The booking process in Skedisy is a streamlined, step-by-step journey that guides you through selecting a salon, service, expert, date, time, and payment method. This section covers the complete booking workflow from start to finish.',
        'doc.step1SelectSalon': 'Step 1: Select Salon',
        'doc.step2ChooseVenue': 'Step 2: Choose Service Venue',
        'doc.step3SelectExpert': 'Step 3: Select Expert',
        'doc.step4ChooseDateTime': 'Step 4: Choose Date & Time',
        'doc.step5SelectPayment': 'Step 5: Select Payment Method',
        'doc.step6ConfirmBooking': 'Step 6: Confirm Booking',
        'doc.bookingProcessFourSteps': 'The booking process consists of four main steps, clearly indicated at the top of each booking screen:',
        'doc.venue': 'Venue',
        'doc.venueDesc': 'Choose service location (At Salon or At Home)',
        'doc.personnel': 'Personnel',
        'doc.personnelDesc': 'Select your preferred expert',
        'doc.dateHeure': 'Date et heure',
        'doc.dateHeureDesc': 'Pick date and time slot',
        'doc.paiement': 'Paiement',
        'doc.paiementDesc': 'Select payment method and confirm',
        'doc.completedStepCheckmark': 'Each completed step shows a checkmark, and the current step is highlighted.',
        'doc.twoWaysDesc': 'You can initiate a booking in two different ways:',
        'doc.bookThroughExpertDesc': 'Start your booking by selecting a specific expert directly from the menu. This option allows you to choose your preferred service provider first, then select the service and salon.',
        'doc.bookThroughExpertCaption': 'Book Through Expert - Select an expert from the menu to start booking',
        'doc.whenBookThroughExpert': 'When you choose to book through an expert:',
        'doc.expertList': 'You\'ll see a list of available experts',
        'doc.expertCard': 'Each expert card displays their profile, ratings, and specialties',
        'doc.tapExpert': 'Tap on an expert to view their available services',
        'doc.selectServiceProceed': 'Select the service you want and proceed with the booking',
        'doc.salonAutoSelected': 'The expert\'s associated salon will be automatically selected',
        'doc.bookThroughSalonDesc': 'Start your booking by selecting a salon first. This is the traditional method where you choose a salon, then select services and experts available at that salon.',
        'doc.bookThroughSalonCaption': 'Book Through Salon - Select a salon to view available services and experts',
        'doc.step1SelectSalonDesc': 'If you chose to book through a salon, begin your booking by choosing a salon from the available options. The salon selection screen is shown in the "Book Through Salon" option above.',
        'doc.salonListingsDesc': 'The "Sélectionnez le salon" (Select the salon) screen displays available salons with:',
        'doc.salonImageDesc': 'Visual preview of the salon interior',
        'doc.salonNameDesc': 'Business name (e.g., "Solivans Hair", "Prestige Paris")',
        'doc.ratingDesc': 'Star rating (e.g., "5.0") displayed with a gold star icon',
        'doc.address': 'Address:',
        'doc.addressDesc': 'Full location with map pin icon',
        'doc.distanceDesc': 'Distance from your location (e.g., "5441.15 KM Depuis votre emplacement")',
        'doc.servicePricesDurations': 'Service prices and durations',
        'doc.availableExpertsStaff': 'Available experts/staff',
        'doc.contactInformation': 'Contact information',
        'doc.directionsCalling': 'Directions and calling options',
        'doc.salonDetailPageDesc': 'On the salon detail page, you\'ll find:',
        'doc.salonImageLarge': 'Large interior photo at the top',
        'doc.salonInformation': 'Salon Information:',
        'doc.salonInformationDesc': 'Name, address, rating, and review count',
        'doc.actionButtons': 'Action Buttons:',
        'doc.actionButtonsDesc': '"Direction" (Directions) and "Appeler le salon" (Call the salon)',
        'doc.serviceTabs': 'Service Tabs:',
        'doc.serviceTabsDesc': '"Prestations de service" (Services), "Product", and "Personnel" (Staff)',
        'doc.serviceCards': 'Service Cards:',
        'doc.serviceCardsDesc': 'Each service shows:',
        'doc.serviceIcon': 'Service icon',
        'doc.serviceName': 'Service name',
        'doc.durationExample': 'Duration (e.g., "30 Minutes", "55 Minutes")',
        'doc.priceExample': 'Price (e.g., "€ 15.00", "€ 30.00")',
        'doc.addButton': 'Add button (green circle with plus sign)',
        'doc.toStartBooking': 'To start booking:',
        'doc.browseServicesTab': 'Browse the services in the "Prestations de service" tab',
        'doc.tapGreenPlus': 'Tap the green plus button on the service you want',
        'doc.serviceAdded': 'The service will be added to your booking',
        'doc.proceedBooking': 'You\'ll proceed to the booking process',
        'doc.selectServiceLocation': 'Select where you want to receive the service - at the salon or at your home.',
        'doc.venueSelectionCaption': 'Venue Selection - Choose between At Salon or At Home',
        'doc.selectServiceVenueScreen': 'The "Select Service Venue" screen offers two options:',
        'doc.atSalon': '"At Salon":',
        'doc.atSalonDesc': 'Service will be performed at the salon location',
        'doc.buildingIcon': 'Shows a building/shop icon',
        'doc.selectedBlackCircle': 'Selected with a black circle and white checkmark',
        'doc.atHome': '"At Home":',
        'doc.atHomeDesc': 'Service will be performed at your location',
        'doc.houseIcon': 'Shows a house icon',
        'doc.unselectedGreyCircle': 'Unselected shows an empty grey circle',
        'doc.makingSelection': 'Making Your Selection',
        'doc.tapPreferredOption': 'Tap on your preferred option. The selected venue will be highlighted with a checkmark. Then tap "Suivant" (Next) to proceed.',
        'doc.someServicesSalonOnly': 'Some services may only be available at the salon. If "At Home" is not available for your selected service, only the "At Salon" option will be shown.',
        'doc.choosePreferredExpert': 'Choose your preferred expert or staff member to perform the service.',
        'doc.expertSelectionCaption': 'Expert Selection - Choose your preferred service provider',
        'doc.chooseExpertScreen': 'The "Choisissez votre expert" (Choose your expert) screen displays available experts in a grid layout:',
        'doc.profilePicture': 'Profile Picture:',
        'doc.profilePictureDesc': 'Circular photo of each expert',
        'doc.expertName': 'Expert Name:',
        'doc.expertNameDesc': 'Full name displayed below the photo',
        'doc.ratingIfAvailable': 'Star rating (if available)',
        'doc.selectionIndicator': 'Selection Indicator:',
        'doc.radioButtonTopRight': 'Radio button in the top right corner',
        'doc.unselectedWhiteCircle': 'Unselected: Empty white circle',
        
        // Step 4: Date & Time Selection
        'doc.step4ChooseDateTimeTitle': 'Step 4: Choose Date & Time',
        'doc.step4ChooseDateTimeDesc': 'Select your preferred date and available time slot for the appointment.',
        'doc.dateTimeSelectionCaption': 'Date and Time Selection - Calendar and time slot picker',
        'doc.dateSelection': 'Date Selection',
        'doc.dateSelectionDesc': 'The "Sélectionner une date" (Select a date) section includes:',
        'doc.currentDateDisplay': 'Current Date Display: Shows the selected month and date (e.g., "2 February, 2026")',
        'doc.monthNavigation': 'Month Navigation: "Feb" with arrow to navigate to other months',
        'doc.calendarView': 'Calendar View: Days of the week (SUN, MON, TUE, WED, THU, FRI, SAT) with dates',
        'doc.selectedDate': 'Selected Date: Highlighted with a light grey background (e.g., "MON 2")',
        'doc.timeSlotSelection': 'Time Slot Selection',
        'doc.timeSlotSelectionDesc': 'The "Créneaux disponibles" (Available slots) section shows:',
        'doc.timeCategories': 'Time Categories: Organized by "Matin" (Morning), "Après-midi" (Afternoon), etc.',
        'doc.availableSlots': 'Available Slots: Displayed as light green buttons with white text (e.g., "09:00 AM", "09:15 AM")',
        'doc.selectedSlots': 'Selected Slots: Displayed as black buttons with white text',
        'doc.unavailableSlots': 'Unavailable Slots: Greyed out or not shown',
        'doc.selectingDateAndTime': 'Selecting Date and Time',
        'doc.toChooseAppointmentTime': 'To choose your appointment time:',
        'doc.tapDateCalendar': 'Tap on a date in the calendar',
        'doc.viewAvailableSlots': 'View available time slots for that date',
        'doc.tapPreferredSlot': 'Tap on your preferred time slot',
        'doc.selectMultipleSlots': 'You can select multiple slots if booking multiple services',
        'doc.selectedSlotsBlack': 'Selected slots will appear in black',
        'doc.tapNextProceedPayment': 'Tap "Suivant" (Next) to proceed to payment',
        'doc.tipTimeSlots': 'Tip: Time slots are typically in 15-minute intervals. If a slot is unavailable, it may be greyed out or not displayed. Book in advance to secure your preferred time.',
        
        // Step 5: Payment Method
        'doc.step5SelectPaymentTitle': 'Step 5: Select Payment Method',
        'doc.chooseHowToPay': 'Choose how you want to pay for your booking.',
        'doc.paymentMethodCaption': 'Payment Method - Choose wallet, Stripe, or cash payment',
        'doc.paymentOptions': 'Payment Options',
        'doc.paymentModeScreen': 'The "Mode de paiement" (Payment Mode) screen offers three payment methods:',
        'doc.myWallet': '"Mon portefeuille" (My wallet):',
        'doc.payUsingWallet': 'Pay using your wallet balance',
        'doc.showsCurrentBalance': 'Shows current balance (e.g., "€ 86.10 dans ton portefeuille")',
        'doc.selectedGreenCheckmark': 'Selected with a green checkmark in a white square',
        'doc.walletIconDisplayed': 'Wallet icon displayed',
        'doc.stripe': '"Stripe":',
        'doc.payWithCard': 'Pay with credit/debit card via Stripe',
        'doc.showsStripeLogo': 'Shows Stripe logo',
        'doc.unselectedWhiteCheckbox': 'Unselected shows empty white checkbox',
        'doc.cashAfterService': '"Cash After Service":',
        'doc.payInCash': 'Pay in cash when the service is completed',
        'doc.showsBanknotesIcon': 'Shows banknotes icon',
        'doc.selectingPaymentMethod': 'Selecting Payment Method',
        'doc.toChoosePaymentMethod': 'To choose a payment method:',
        'doc.reviewPaymentOptions': 'Review the available payment options',
        'doc.checkWalletBalance': 'Check your wallet balance if using wallet payment',
        'doc.tapPreferredMethod': 'Tap on your preferred payment method',
        'doc.selectedMethodCheckmark': 'The selected method will show a checkmark',
        'doc.reviewPriceBreakdown': 'Review the price breakdown at the bottom',
        'doc.tapConfirmProceed': 'Tap "Confirmer" (Confirm) to proceed',
        'doc.priceSummary': 'Price Summary',
        'doc.bottomScreenShows': 'The bottom of the screen shows:',
        'doc.serviceName': 'Service Name: The selected service (e.g., "Blow Dry & Styling")',
        'doc.priceBreakdown': 'Price Breakdown: Base price + tax = total',
        'doc.priceExample': 'Example: "€ 15.00 (€2.70 Impôt) = € 17.70"',
        'doc.basePrice': 'Base price: €15.00',
        'doc.tax': 'Tax (Impôt): €2.70',
        'doc.total': 'Total: €17.70',
        'doc.importantWalletPayment': 'Important: If using wallet payment, ensure your balance is sufficient to cover the total amount (including tax). If your balance is insufficient, you\'ll need to recharge your wallet or choose another payment method.',
        
        // Step 6: Confirm Booking
        'doc.step6ConfirmBookingTitle': 'Step 6: Confirm Booking',
        'doc.reviewBookingDetails': 'Review your booking details and confirm the reservation.',
        'doc.bookingConfirmationCaption': 'Booking Confirmation - Final confirmation dialog',
        'doc.confirmationDialog': 'Confirmation Dialog',
        'doc.afterSelectingPayment': 'After selecting payment method and tapping "Confirmer", a confirmation popup appears with:',
        'doc.header': 'Header:',
        'doc.confirmReservation': '"Confirmer la réservation" (Confirm the reservation) in black header',
        'doc.serviceNameDisplayed': 'Service Name: Displayed with a green checkmark (e.g., "Blow Dry & Styling")',
        'doc.confirmationQuestion': 'Confirmation Question:',
        'doc.confirmReservationQuestion': '"Voulez-vous confirmer cette réservation?" (Do you want to confirm this reservation?)',
        'doc.termsCheckbox': 'Terms Checkbox:',
        'doc.termsCheckboxText': '"J\'ai lu l\'avertissement et je suis d\'accord sur les termes et conditions." (I have read the warning and I agree to the terms and conditions.)',
        'doc.acceptingTerms': 'Accepting Terms',
        'doc.beforeConfirming': 'Before confirming:',
        'doc.readTerms': 'Read the terms and conditions',
        'doc.checkCheckbox': 'Check the checkbox to accept the terms',
        'doc.checkboxMustBeChecked': 'The checkbox must be checked to proceed',
        'doc.finalConfirmation': 'Final Confirmation',
        'doc.dialogTwoOptions': 'The dialog provides two options:',
        'doc.cancelButton': '"Annuler" (Cancel): White button to go back and make changes',
        'doc.confirmButton': '"Confirmer" (Confirm): Green button to finalize the booking',
        'doc.onceTapConfirm': 'Once you tap "Confirmer", your booking will be processed and confirmed.',
        'doc.afterConfirmation': 'After Confirmation',
        'doc.afterConfirmingBooking': 'After confirming your booking:',
        'doc.receiveConfirmation': 'You\'ll receive a booking confirmation',
        'doc.bookingIdGenerated': 'A booking ID will be generated',
        'doc.receiveNotification': 'You\'ll receive a notification about the booking',
        'doc.bookingAppears': 'The booking will appear in your "Booking" screen',
        'doc.viewModifyCancel': 'You can view, modify, or cancel it from there',
        'doc.noteConfirmDetails': 'Note: Make sure all details are correct before confirming. Once confirmed, you may need to contact the salon directly to make changes, depending on their cancellation policy.',
        'doc.bookingProcessSummary': 'Booking Process Summary',
        'doc.completeBookingProcess': 'The complete booking process follows these steps:',
        'doc.selectSalonStep': 'Select Salon: Browse and choose a salon, then select a service',
        'doc.chooseVenueStep': 'Choose Venue: Decide between "At Salon" or "At Home"',
        'doc.selectExpertStep': 'Select Expert: Choose your preferred service provider',
        'doc.pickDateTimeStep': 'Pick Date & Time: Select your preferred appointment slot',
        'doc.paymentMethodStep': 'Payment Method: Choose wallet, Stripe, or cash payment',
        'doc.confirmStep': 'Confirm: Review and confirm your booking',
        'doc.tipSaveFavorites': 'Tip: You can save your favorite salons and experts for faster booking in the future. Also, ensure your wallet is funded if you plan to use wallet payment.'
    },
    fr: {
        // Navigation
        'nav.aiConcierge': 'Concierge IA',
        'nav.documentation': 'Documentation',
        'nav.menu': 'Menu',
        'nav.login': 'Connecter',
        
        // Hero Section
        'hero.title': 'La Plateforme #1 pour Gérer Votre Salon',
        'hero.subtitle': '<strong>50 000+ salons</strong> nous font confiance. <strong>10M+ d\'utilisateurs</strong> chaque mois.',
        'hero.addSalon': 'Ajouter',
        'hero.tryAI': 'Essayer',
        'hero.trustBadge': '4,8/5 sur Trustpilot',
        'hero.bookingManagement': 'Gestion des réservations',
        'hero.simplifiedPayments': 'Paiements simplifiés',
        'hero.noCommitment': 'Sans engagement',
        
        // Request Buttons
        'request.salonTitle': 'Intégrer votre salon sur Skedisy ?',
        'request.salonButton': 'Demander',
        'request.customerTitle': 'Réserver des services ?',
        'request.customerButton': 'Réserver',
        
        // Stats
        'stats.professionals': 'Professionnels',
        'stats.appointments': 'Rendez-vous mensuels',
        'stats.onlineBookings': 'Réservations hors heures',
        
        // Features
        'features.bookTitle': 'Réservez en Ligne',
        'features.bookDesc': 'Trouvez votre salon et réservez 24/7. Quelques clics suffisent !',
        'features.manageTitle': 'Gérez Votre Salon',
        'features.manageDesc': 'Gérez réservations, personnel et horaires depuis n\'importe où.',
        
        // New Clients
        'clients.title': 'Nouveaux Clients.<br>En Continu.',
        'clients.desc': 'Laissez-les vous trouver.',
        'clients.showcase': 'Page de présentation',
        'clients.reviews': 'Avis certifiés',
        'clients.ranking': 'Classement Google',
        'clients.discover': 'Découvrir',
        
        // Professional Stats
        'proStats.title': 'Professionnel de la beauté ?<br>Découvrez la réservation en ligne !',
        'proStats.increase': 'd\'augmentation des réservations en ligne',
        'proStats.noShows': 'moins d\'absences avec SMS',
        'proStats.outsideHours': 'réservations hors heures',
        'proStats.salons': 'Salons & instituts',
        'proStats.booked': 'Réservé chaque seconde',
        'proStats.sold': 'en rendez-vous vendus',
        
        // Platform Features
        'platform.manage': 'Gérer',
        'platform.manageDesc': 'Contrôlez tout : réservations, ventes, équipe.',
        'platform.grow': 'Croître',
        'platform.growDesc': 'Nouveaux clients et fidélisation.',
        'platform.getPaid': 'Se Faire Payer',
        'platform.getPaidDesc': 'Paiements rapides. Moins d\'absences.',
        'platform.aiTitle': 'Concierge Beauté IA',
        'platform.aiDesc': 'Recommandations beauté personnalisées par IA.',
        'platform.tryNow': 'Essayer →',
        
        // CTA
        'cta.ready': 'Prêt à développer votre entreprise ?',
        'cta.join': 'Rejoignez des milliers de pros. Gratuit !',
        'cta.getStarted': 'Commencer',
        'cta.million': '10 000 000',
        'cta.millionDesc': '10M de réservations beauté chaque mois.',
        'cta.final': '50 000+ professionnels nous font confiance.',
        
        // FAQ
        'faq.title': 'Questions Fréquentes',
        'faq.customerAccount': 'Comment créer un compte client ?',
        'faq.salonAccount': 'Comment créer un compte propriétaire ?',
        'faq.expertCredentials': 'Comment obtenir les identifiants expert ?',
        'faq.downloadApp': 'Comment télécharger l\'app ?',
        'faq.appDifference': 'Différence entre app Client et Expert ?',
        'faq.bookService': 'Comment réserver un service ?',
        'faq.acceptReservation': 'Comment accepter/refuser une réservation ?',
        'faq.manageBusiness': 'Comment gérer son salon (experts, services) ?',
        'faq.newClients': 'SalonPortal m\'apportera-t-il de nouveaux clients ?',
        'faq.newClientsDesc': 'Visible par 10M d\'utilisateurs et sur Google.',
        
        // Footer
        'footer.tagline': 'Gérez votre salon avec notre solution tout-en-un.',
        'footer.about': 'À Propos',
        'footer.myAccount': 'Mon Compte Skedisy',
        'footer.signUp': 'Inscrire',
        'footer.pricing': 'Tarification',
        'footer.helpCenter': 'Centre d\'Aide',
        'footer.solutions': 'Nos Solutions',
        'footer.onlineBooking': 'Réservation en Ligne 24/7',
        'footer.calendar': 'Gestion du Calendrier',
        'footer.pos': 'TPV Certifié',
        'footer.payment': 'Terminal de Paiement',
        'footer.workTime': 'Gestion du Temps de Travail',
        'footer.marketing': 'Solutions Marketing',
        'footer.legal': 'Légal',
        'footer.terms': 'Conditions d\'Utilisation',
        'footer.privacy': 'Politique de Confidentialité',
        'footer.cookies': 'Gestion des Cookies',
        'footer.rights': '© 2024 Skedisy. Tous droits réservés.',
        
        // Modal
        'modal.choosePlatform': 'Plateforme',
        'modal.selectDevice': 'Appareil',
        'modal.android': 'Android',
        'modal.downloadAndroid': 'Télécharger depuis Google Play',
        'modal.download': 'Télécharger',
        'modal.iphone': 'iPhone',
        'modal.downloadIOS': 'Télécharger depuis l\'App Store',
        'modal.requestDemo': 'Démo',
        'modal.sendRequest': 'Envoyez votre demande à :',
        'modal.includeInfo': 'Informations à inclure :',
        'modal.managerName': 'Nom du Gérant',
        'modal.phoneNumber': 'Téléphone',
        'modal.emailAddress': 'E-mail',
        'modal.establishmentType': 'Type d\'Établissement ?',
        
        // QR Code
        'qr.customerApp': 'Télécharger l\'Application Client',
        'qr.expertApp': 'Télécharger l\'Application Expert',
        
        // Language Switcher
        'lang.english': 'English',
        'lang.french': 'Français',
        'lang.switchTo': 'Changer pour',
        
        // Documentation
        'doc.documentation': 'Documentation',
        'doc.customerApp': 'Application Client',
        'doc.expertApp': 'Application Expert',
        'doc.salonOwnerPortal': 'Portail Propriétaire',
        'doc.gettingStarted': 'Commencer',
        'doc.homeScreen': 'Écran d\'Accueil',
        'doc.bookingProcess': 'Processus de Réservation',
        'doc.bookingScreen': 'Écran de Réservation',
        'doc.productCategory': 'Catégorie de Produits',
        'doc.notifications': 'Notifications',
        'doc.profile': 'Profil',
        'doc.wallet': 'Portefeuille',
        'doc.myRevenue': 'Mes Revenus',
        'doc.reservationDetails': 'Détails des Réservations',
        'doc.slotManagement': 'Gestion des Créneaux',
        'doc.orderDetails': 'Détails des Commandes',
        'doc.expertProfile': 'Profil Expert',
        'doc.dashboard': 'Tableau de Bord',
        'doc.expertsManagement': 'Gestion des Experts',
        'doc.reviews': 'Avis',
        'doc.complaints': 'Réclamations',
        'doc.expertAttendance': 'Présence des Experts',
        'doc.orders': 'Commandes',
        'doc.services': 'Services',
        'doc.products': 'Produits',
        'doc.attributes': 'Attributs',
        'doc.salonTime': 'Horaires du Salon',
        'doc.salonHoliday': 'Congés du Salon',
        'doc.walletHistory': 'Historique du Portefeuille',
        'doc.withdrawMoney': 'Retirer de l\'Argent',
        'doc.customerAppWelcome': 'Guide complet de l\'app client Skedisy pour réserver vos rendez-vous.',
        'doc.tableOfContentsCustomer': 'Table des Matières - Application Client',
        'doc.lookingForExpertApp': 'Vous cherchez la documentation de l\'application Expert ?',
        'doc.clickHere': 'Cliquez ici',
        'doc.note': 'Note :',
        'doc.customerAppNote': 'App mobile intuitive pour réserver et gérer vos rendez-vous.',
        'doc.homeScreenDesc': 'Point d\'entrée : catégories, salons proches, recherche.',
        'doc.expertAppWelcome': 'Guide pour les experts : réservations, revenus, horaires.',
        'doc.salonOwnerPortalWelcome': 'Guide du portail propriétaire : gérer salon, personnel, services.',
        
        // Documentation - Common Sections (French)
        'doc.headerSection': 'Section En-tête',
        'doc.categorySection': 'Section Catégories',
        'doc.nearbySalonsSection': 'Section Salons Proches',
        'doc.bottomNavigation': 'Navigation Inférieure',
        'doc.brandNameLocation': 'Nom de la Marque & Localisation',
        'doc.actionIcons': 'Icônes d\'Action',
        'doc.searchBar': 'Barre de Recherche',
        'doc.viewingSalonDetails': 'Voir les Détails du Salon',
        'doc.bookingSteps': 'Étapes de Réservation',
        'doc.bookingProcessOverview': 'Aperçu du Processus de Réservation',
        'doc.twoWaysToStart': 'Deux Façons de Commencer une Réservation',
        'doc.bookThroughExpert': 'Réserver via un Expert',
        'doc.bookThroughSalon': 'Réserver via un Salon',
        'doc.selectSalon': 'Sélectionner un Salon',
        'doc.chooseServiceVenue': 'Choisir le Lieu du Service',
        'doc.selectExpert': 'Sélectionner un Expert',
        'doc.chooseDateTime': 'Choisir la Date & l\'Heure',
        'doc.selectPaymentMethod': 'Sélectionner le Mode de Paiement',
        'doc.confirmBooking': 'Confirmer la Réservation',
        'doc.salonListings': 'Liste des Salons',
        'doc.salonDetailPage': 'Page de Détails du Salon',
        'doc.selectingService': 'Sélection d\'un Service',
        'doc.venueSelection': 'Sélection du Lieu',
        'doc.expertSelection': 'Sélection de l\'Expert',
        'doc.expertDetails': 'Détails de l\'Expert',
        'doc.dateTimeSelection': 'Sélection de la Date et de l\'Heure',
        'doc.paymentMethod': 'Mode de Paiement',
        'doc.bookingConfirmation': 'Confirmation de Réservation',
        'doc.completeServiceOfferings': 'Offres de services complètes',
        'doc.availableTimeSlots': 'Créneaux horaires disponibles',
        'doc.expertProfiles': 'Profils d\'experts',
        'doc.pricingInformation': 'Informations sur les prix',
        'doc.customerReviews': 'Avis clients',
        'doc.heartIcon': 'Icône Cœur',
        'doc.shoppingBagIcon': 'Icône Sac de Courses',
        'doc.accessFavorites': 'Accéder à vos favoris et salons enregistrés',
        'doc.viewCart': 'Voir votre panier ou réservations en cours',
        'doc.findServices': 'Recherchez des services par mot-clé (ex: coupe, manucure).',
        'doc.categoryList': 'Sous la barre de recherche, vous trouverez une liste horizontale défilable de catégories de services. Chaque catégorie est représentée par:',
        'doc.iconLabel': 'Icône: Représentation visuelle du type de service',
        'doc.categoryName': 'Libellé: Nom de la catégorie (ex: "Soins du Corps", "Services de Maquillage", "Soins des Ongles", "Services Capillaires", "Peau & Visage")',
        'doc.tapCategory': 'Appuyez sur une catégorie pour voir les services disponibles dans cette catégorie. Vous pouvez également appuyer sur "Voir Tout" pour voir toutes les catégories à la fois.',
        'doc.nearbySalonsDesc': 'Salons proches affichés par distance :',
        'doc.salonImage': 'Image du Salon: Aperçu visuel de l\'intérieur du salon',
        'doc.salonName': 'Nom du Salon: Le nom de l\'établissement',
        'doc.rating': 'Note: Note étoilée et score d\'avis',
        'doc.location': 'Localisation: Adresse complète avec icône d\'épingle de carte',
        'doc.distance': 'Distance: Distance de votre localisation actuelle en kilomètres',
        'doc.status': 'Statut: Indicateur Ouvert/Fermé avec bouton codé par couleur',
        'doc.favoriteIcon': 'Icône Favori: Icône cœur pour sauvegarder le salon dans vos favoris',
        'doc.tapSalonCard': 'Appuyez sur une carte de salon pour voir des informations détaillées, notamment:',
        'doc.bottomNavDesc': 'Accès rapide aux sections principales :',
        'doc.homeIcon': 'Accueil (Icône Maison): Retourner à l\'écran d\'accueil',
        'doc.calendar': 'Calendrier: Voir vos rendez-vous et réservations',
        'doc.shoppingBag': 'Sac de Courses: Accéder à votre panier et réservations',
        'doc.bell': 'Cloche: Voir les notifications',
        'doc.profile': 'Profil: Accéder aux paramètres de votre compte et portefeuille',
        'doc.topLeftDisplays': 'En haut à gauche s\'affiche le nom de la marque "Skedisy" avec votre indicateur de localisation (ex: "Nb" pour votre zone actuelle).',
        'doc.topRightIcons': 'En haut à droite, vous trouverez deux icônes en contour:',
        'doc.option1': 'Option 1',
        'doc.option2': 'Option 2',
        'doc.step1': 'Étape 1',
        'doc.step2': 'Étape 2',
        'doc.step3': 'Étape 3',
        'doc.step4': 'Étape 4',
        'doc.step5': 'Étape 5',
        'doc.step6': 'Étape 6',
        'doc.bookingProcessDesc': 'Réservation en plusieurs étapes : salon, service, expert, date, paiement.',
        'doc.step1SelectSalon': 'Étape 1 : Sélectionner un Salon',
        'doc.step2ChooseVenue': 'Étape 2 : Choisir le Lieu du Service',
        'doc.step3SelectExpert': 'Étape 3 : Sélectionner un Expert',
        'doc.step4ChooseDateTime': 'Étape 4 : Choisir la Date & l\'Heure',
        'doc.step5SelectPayment': 'Étape 5 : Sélectionner le Mode de Paiement',
        'doc.step6ConfirmBooking': 'Étape 6 : Confirmer la Réservation',
        'doc.bookingProcessFourSteps': 'Le processus de réservation consiste en quatre étapes principales, clairement indiquées en haut de chaque écran de réservation:',
        'doc.venue': 'Lieu',
        'doc.venueDesc': 'Choisir le lieu du service (Au Salon ou À Domicile)',
        'doc.personnel': 'Personnel',
        'doc.personnelDesc': 'Sélectionner votre expert préféré',
        'doc.dateHeure': 'Date et heure',
        'doc.dateHeureDesc': 'Choisir la date et le créneau horaire',
        'doc.paiement': 'Paiement',
        'doc.paiementDesc': 'Sélectionner le mode de paiement et confirmer',
        'doc.completedStepCheckmark': 'Chaque étape terminée affiche une coche, et l\'étape actuelle est mise en surbrillance.',
        'doc.twoWaysDesc': 'Vous pouvez initier une réservation de deux façons différentes:',
        'doc.bookThroughExpertDesc': 'Commencez votre réservation en sélectionnant un expert spécifique directement depuis le menu. Cette option vous permet de choisir d\'abord votre prestataire de services préféré, puis de sélectionner le service et le salon.',
        'doc.bookThroughExpertCaption': 'Réserver via un Expert - Sélectionnez un expert dans le menu pour commencer la réservation',
        'doc.whenBookThroughExpert': 'Lorsque vous choisissez de réserver via un expert:',
        'doc.expertList': 'Vous verrez une liste d\'experts disponibles',
        'doc.expertCard': 'Chaque carte d\'expert affiche son profil, ses notes et ses spécialités',
        'doc.tapExpert': 'Appuyez sur un expert pour voir ses services disponibles',
        'doc.selectServiceProceed': 'Sélectionnez le service souhaité et poursuivez la réservation',
        'doc.salonAutoSelected': 'Le salon associé à l\'expert sera automatiquement sélectionné',
        'doc.bookThroughSalonDesc': 'Commencez votre réservation en sélectionnant d\'abord un salon. C\'est la méthode traditionnelle où vous choisissez un salon, puis sélectionnez les services et les experts disponibles dans ce salon.',
        'doc.bookThroughSalonCaption': 'Réserver via un Salon - Sélectionnez un salon pour voir les services et experts disponibles',
        'doc.step1SelectSalonDesc': 'Si vous avez choisi de réserver via un salon, commencez votre réservation en choisissant un salon parmi les options disponibles. L\'écran de sélection de salon est affiché dans l\'option "Réserver via un Salon" ci-dessus.',
        'doc.salonListingsDesc': 'L\'écran "Sélectionnez le salon" affiche les salons disponibles avec:',
        'doc.salonImageDesc': 'Aperçu visuel de l\'intérieur du salon',
        'doc.salonNameDesc': 'Nom de l\'établissement (ex: "Solivans Hair", "Prestige Paris")',
        'doc.ratingDesc': 'Note étoilée (ex: "5.0") affichée avec une icône d\'étoile dorée',
        'doc.address': 'Adresse:',
        'doc.addressDesc': 'Localisation complète avec icône d\'épingle de carte',
        'doc.distanceDesc': 'Distance de votre localisation (ex: "5441.15 KM Depuis votre emplacement")',
        'doc.servicePricesDurations': 'Prix et durées des services',
        'doc.availableExpertsStaff': 'Experts/personnel disponibles',
        'doc.contactInformation': 'Informations de contact',
        'doc.directionsCalling': 'Itinéraires et options d\'appel',
        'doc.salonDetailPageDesc': 'Sur la page de détails du salon, vous trouverez:',
        'doc.salonImageLarge': 'Grande photo intérieure en haut',
        'doc.salonInformation': 'Informations du Salon:',
        'doc.salonInformationDesc': 'Nom, adresse, note et nombre d\'avis',
        'doc.actionButtons': 'Boutons d\'Action:',
        'doc.actionButtonsDesc': '"Direction" et "Appeler le salon"',
        'doc.serviceTabs': 'Onglets de Services:',
        'doc.serviceTabsDesc': '"Prestations de service", "Product" et "Personnel"',
        'doc.serviceCards': 'Cartes de Services:',
        'doc.serviceCardsDesc': 'Chaque service affiche:',
        'doc.serviceIcon': 'Icône du service',
        'doc.serviceName': 'Nom du service',
        'doc.durationExample': 'Durée (ex: "30 Minutes", "55 Minutes")',
        'doc.priceExample': 'Prix (ex: "€ 15.00", "€ 30.00")',
        'doc.addButton': 'Bouton d\'ajout (cercle vert avec signe plus)',
        'doc.toStartBooking': 'Pour commencer la réservation:',
        'doc.browseServicesTab': 'Parcourez les services dans l\'onglet "Prestations de service"',
        'doc.tapGreenPlus': 'Appuyez sur le bouton vert plus sur le service souhaité',
        'doc.serviceAdded': 'Le service sera ajouté à votre réservation',
        'doc.proceedBooking': 'Vous passerez au processus de réservation',
        'doc.selectServiceLocation': 'Sélectionnez où vous souhaitez recevoir le service - au salon ou à domicile.',
        'doc.venueSelectionCaption': 'Sélection du Lieu - Choisissez entre Au Salon ou À Domicile',
        'doc.selectServiceVenueScreen': 'L\'écran "Sélectionner le Lieu du Service" propose deux options:',
        'doc.atSalon': '"Au Salon":',
        'doc.atSalonDesc': 'Le service sera effectué à l\'emplacement du salon',
        'doc.buildingIcon': 'Affiche une icône de bâtiment/boutique',
        'doc.selectedBlackCircle': 'Sélectionné avec un cercle noir et une coche blanche',
        'doc.atHome': '"À Domicile":',
        'doc.atHomeDesc': 'Le service sera effectué à votre emplacement',
        'doc.houseIcon': 'Affiche une icône de maison',
        'doc.unselectedGreyCircle': 'Non sélectionné affiche un cercle gris vide',
        'doc.makingSelection': 'Faire Votre Sélection',
        'doc.tapPreferredOption': 'Appuyez sur votre option préférée. Le lieu sélectionné sera mis en surbrillance avec une coche. Ensuite, appuyez sur "Suivant" pour continuer.',
        'doc.someServicesSalonOnly': 'Certains services peuvent être disponibles uniquement au salon. Si "À Domicile" n\'est pas disponible pour votre service sélectionné, seule l\'option "Au Salon" sera affichée.',
        'doc.choosePreferredExpert': 'Choisissez votre expert ou membre du personnel préféré pour effectuer le service.',
        'doc.expertSelectionCaption': 'Sélection de l\'Expert - Choisissez votre prestataire de services préféré',
        'doc.chooseExpertScreen': 'L\'écran "Choisissez votre expert" affiche les experts disponibles dans une mise en page en grille:',
        'doc.profilePicture': 'Photo de Profil:',
        'doc.profilePictureDesc': 'Photo circulaire de chaque expert',
        'doc.expertName': 'Nom de l\'Expert:',
        'doc.expertNameDesc': 'Nom complet affiché sous la photo',
        'doc.ratingIfAvailable': 'Note étoilée (si disponible)',
        'doc.selectionIndicator': 'Indicateur de Sélection:',
        'doc.radioButtonTopRight': 'Bouton radio dans le coin supérieur droit',
        'doc.unselectedWhiteCircle': 'Non sélectionné: Cercle blanc vide',
        
        // Step 4: Date & Time Selection (French)
        'doc.step4ChooseDateTimeTitle': 'Étape 4 : Choisir la Date & l\'Heure',
        'doc.step4ChooseDateTimeDesc': 'Sélectionnez votre date préférée et le créneau horaire disponible pour le rendez-vous.',
        'doc.dateTimeSelectionCaption': 'Sélection de la Date et de l\'Heure - Calendrier et sélecteur de créneaux',
        'doc.dateSelection': 'Sélection de la Date',
        'doc.dateSelectionDesc': 'La section "Sélectionner une date" comprend :',
        'doc.currentDateDisplay': 'Affichage de la Date Actuelle : Affiche le mois et la date sélectionnés (ex: "2 février 2026")',
        'doc.monthNavigation': 'Navigation Mensuelle : "Fév" avec flèche pour naviguer vers d\'autres mois',
        'doc.calendarView': 'Vue Calendrier : Jours de la semaine (DIM, LUN, MAR, MER, JEU, VEN, SAM) avec dates',
        'doc.selectedDate': 'Date Sélectionnée : Mise en surbrillance avec un fond gris clair (ex: "LUN 2")',
        'doc.timeSlotSelection': 'Sélection des Créneaux Horaires',
        'doc.timeSlotSelectionDesc': 'La section "Créneaux disponibles" affiche :',
        'doc.timeCategories': 'Catégories de Temps : Organisées par "Matin", "Après-midi", etc.',
        'doc.availableSlots': 'Créneaux Disponibles : Affichés sous forme de boutons vert clair avec texte blanc (ex: "09:00", "09:15")',
        'doc.selectedSlots': 'Créneaux Sélectionnés : Affichés sous forme de boutons noirs avec texte blanc',
        'doc.unavailableSlots': 'Créneaux Indisponibles : Grisés ou non affichés',
        'doc.selectingDateAndTime': 'Sélectionner la Date et l\'Heure',
        'doc.toChooseAppointmentTime': 'Pour choisir l\'heure de votre rendez-vous :',
        'doc.tapDateCalendar': 'Appuyez sur une date dans le calendrier',
        'doc.viewAvailableSlots': 'Consultez les créneaux horaires disponibles pour cette date',
        'doc.tapPreferredSlot': 'Appuyez sur votre créneau horaire préféré',
        'doc.selectMultipleSlots': 'Vous pouvez sélectionner plusieurs créneaux si vous réservez plusieurs services',
        'doc.selectedSlotsBlack': 'Les créneaux sélectionnés apparaîtront en noir',
        'doc.tapNextProceedPayment': 'Appuyez sur "Suivant" pour procéder au paiement',
        'doc.tipTimeSlots': 'Astuce : Les créneaux horaires sont généralement espacés de 15 minutes. Si un créneau est indisponible, il peut être grisé ou non affiché. Réservez à l\'avance pour sécuriser votre heure préférée.',
        
        // Step 5: Payment Method (French)
        'doc.step5SelectPaymentTitle': 'Étape 5 : Sélectionner le Mode de Paiement',
        'doc.chooseHowToPay': 'Choisissez comment vous souhaitez payer votre réservation.',
        'doc.paymentMethodCaption': 'Mode de Paiement - Choisissez portefeuille, Stripe ou paiement en espèces',
        'doc.paymentOptions': 'Options de Paiement',
        'doc.paymentModeScreen': 'L\'écran "Mode de paiement" propose trois modes de paiement :',
        'doc.myWallet': '"Mon portefeuille" :',
        'doc.payUsingWallet': 'Payer en utilisant le solde de votre portefeuille',
        'doc.showsCurrentBalance': 'Affiche le solde actuel (ex: "€ 86.10 dans ton portefeuille")',
        'doc.selectedGreenCheckmark': 'Sélectionné avec une coche verte dans un carré blanc',
        'doc.walletIconDisplayed': 'Icône de portefeuille affichée',
        'doc.stripe': '"Stripe" :',
        'doc.payWithCard': 'Payer par carte de crédit/débit via Stripe',
        'doc.showsStripeLogo': 'Affiche le logo Stripe',
        'doc.unselectedWhiteCheckbox': 'Non sélectionné affiche une case blanche vide',
        'doc.cashAfterService': '"Espèces après Service" :',
        'doc.payInCash': 'Payer en espèces lorsque le service est terminé',
        'doc.showsBanknotesIcon': 'Affiche une icône de billets',
        'doc.selectingPaymentMethod': 'Sélectionner le Mode de Paiement',
        'doc.toChoosePaymentMethod': 'Pour choisir un mode de paiement :',
        'doc.reviewPaymentOptions': 'Consultez les options de paiement disponibles',
        'doc.checkWalletBalance': 'Vérifiez le solde de votre portefeuille si vous utilisez le paiement par portefeuille',
        'doc.tapPreferredMethod': 'Appuyez sur votre mode de paiement préféré',
        'doc.selectedMethodCheckmark': 'Le mode sélectionné affichera une coche',
        'doc.reviewPriceBreakdown': 'Consultez le détail des prix en bas',
        'doc.tapConfirmProceed': 'Appuyez sur "Confirmer" pour continuer',
        'doc.priceSummary': 'Résumé des Prix',
        'doc.bottomScreenShows': 'Le bas de l\'écran affiche :',
        'doc.serviceName': 'Nom du Service : Le service sélectionné (ex: "Séchage & Coiffage")',
        'doc.priceBreakdown': 'Détail des Prix : Prix de base + taxe = total',
        'doc.priceExample': 'Exemple : "€ 15.00 (€2.70 Impôt) = € 17.70"',
        'doc.basePrice': 'Prix de base : €15.00',
        'doc.tax': 'Taxe (Impôt) : €2.70',
        'doc.total': 'Total : €17.70',
        'doc.importantWalletPayment': 'Important : Si vous utilisez le paiement par portefeuille, assurez-vous que votre solde est suffisant pour couvrir le montant total (taxe comprise). Si votre solde est insuffisant, vous devrez recharger votre portefeuille ou choisir un autre mode de paiement.',
        
        // Step 6: Confirm Booking (French)
        'doc.step6ConfirmBookingTitle': 'Étape 6 : Confirmer la Réservation',
        'doc.reviewBookingDetails': 'Consultez les détails de votre réservation et confirmez la réservation.',
        'doc.bookingConfirmationCaption': 'Confirmation de Réservation - Dialogue de confirmation final',
        'doc.confirmationDialog': 'Dialogue de Confirmation',
        'doc.afterSelectingPayment': 'Après avoir sélectionné le mode de paiement et appuyé sur "Confirmer", une popup de confirmation apparaît avec :',
        'doc.header': 'En-tête :',
        'doc.confirmReservation': '"Confirmer la réservation" dans un en-tête noir',
        'doc.serviceNameDisplayed': 'Nom du Service : Affiché avec une coche verte (ex: "Séchage & Coiffage")',
        'doc.confirmationQuestion': 'Question de Confirmation :',
        'doc.confirmReservationQuestion': '"Voulez-vous confirmer cette réservation ?"',
        'doc.termsCheckbox': 'Case à Cocher des Conditions :',
        'doc.termsCheckboxText': '"J\'ai lu l\'avertissement et je suis d\'accord sur les termes et conditions."',
        'doc.acceptingTerms': 'Accepter les Conditions',
        'doc.beforeConfirming': 'Avant de confirmer :',
        'doc.readTerms': 'Lisez les termes et conditions',
        'doc.checkCheckbox': 'Cochez la case pour accepter les conditions',
        'doc.checkboxMustBeChecked': 'La case doit être cochée pour continuer',
        'doc.finalConfirmation': 'Confirmation Finale',
        'doc.dialogTwoOptions': 'Le dialogue propose deux options :',
        'doc.cancelButton': '"Annuler" : Bouton blanc pour revenir en arrière et apporter des modifications',
        'doc.confirmButton': '"Confirmer" : Bouton vert pour finaliser la réservation',
        'doc.onceTapConfirm': 'Une fois que vous appuyez sur "Confirmer", votre réservation sera traitée et confirmée.',
        'doc.afterConfirmation': 'Après la Confirmation',
        'doc.afterConfirmingBooking': 'Après avoir confirmé votre réservation :',
        'doc.receiveConfirmation': 'Vous recevrez une confirmation de réservation',
        'doc.bookingIdGenerated': 'Un ID de réservation sera généré',
        'doc.receiveNotification': 'Vous recevrez une notification concernant la réservation',
        'doc.bookingAppears': 'La réservation apparaîtra dans votre écran "Réservation"',
        'doc.viewModifyCancel': 'Vous pouvez la consulter, la modifier ou l\'annuler depuis là',
        'doc.noteConfirmDetails': 'Note : Assurez-vous que tous les détails sont corrects avant de confirmer. Une fois confirmée, vous devrez peut-être contacter directement le salon pour apporter des modifications, selon leur politique d\'annulation.',
        'doc.bookingProcessSummary': 'Résumé du Processus de Réservation',
        'doc.completeBookingProcess': 'Le processus de réservation complet suit ces étapes :',
        'doc.selectSalonStep': 'Sélectionner un Salon : Parcourez et choisissez un salon, puis sélectionnez un service',
        'doc.chooseVenueStep': 'Choisir le Lieu : Décidez entre "Au Salon" ou "À Domicile"',
        'doc.selectExpertStep': 'Sélectionner un Expert : Choisissez votre prestataire de services préféré',
        'doc.pickDateTimeStep': 'Choisir la Date & l\'Heure : Sélectionnez votre créneau de rendez-vous préféré',
        'doc.paymentMethodStep': 'Mode de Paiement : Choisissez portefeuille, Stripe ou paiement en espèces',
        'doc.confirmStep': 'Confirmer : Consultez et confirmez votre réservation',
        'doc.tipSaveFavorites': 'Astuce : Vous pouvez enregistrer vos salons et experts favoris pour une réservation plus rapide à l\'avenir. Assurez-vous également que votre portefeuille est approvisionné si vous prévoyez d\'utiliser le paiement par portefeuille.'
    }
};

// Language Management
let currentLanguage = localStorage.getItem('skedisy-language') || 'fr';

function setLanguage(lang) {
    if (!translations[lang]) return;
    currentLanguage = lang;
    localStorage.setItem('skedisy-language', lang);
    document.documentElement.lang = lang;
    translatePage();
    updateLanguageSwitcher();
    
    // Reload categories with new language if loadCategories function exists
    if (typeof loadCategories === 'function') {
        loadCategories();
    }
}

function getTranslation(key) {
    return translations[currentLanguage]?.[key] || translations['fr'][key] || translations['en'][key] || key;
}

function translatePage() {
    // Find all elements with data-translate attribute (excludes data-translate-html only)
    document.querySelectorAll('[data-translate]:not([data-translate-html])').forEach(element => {
        const key = element.getAttribute('data-translate');
        const translation = getTranslation(key);
        
        if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
            element.placeholder = translation;
        } else {
            // Use replaceChildren to prevent any duplication - ensures clean single replacement
            element.replaceChildren(document.createTextNode(translation));
        }
    });
    
    // Process data-translate-html elements (allows HTML in translation)
    document.querySelectorAll('[data-translate-html]').forEach(element => {
        const key = element.getAttribute('data-translate-html');
        const translation = getTranslation(key);
        element.innerHTML = translation;
    });
    
    // Update page title
    const titleElement = document.querySelector('title[data-translate]');
    if (titleElement) {
        document.title = getTranslation(titleElement.getAttribute('data-translate'));
    }
}

function updateLanguageSwitcher() {
    const switchers = document.querySelectorAll('.lang-switcher');
    switchers.forEach(switcher => {
        const newLang = currentLanguage === 'fr' ? 'en' : 'fr';
        const newLangName = currentLanguage === 'fr' ? 'English' : 'Français';
        const shortName = currentLanguage === 'fr' ? 'EN' : 'FR';
        
        // Update data-lang attribute
        switcher.setAttribute('data-lang', newLang);
        
        // Update text content - preserve icon if it exists
        const icon = switcher.querySelector('i');
        const span = switcher.querySelector('span');
        
        if (span) {
            // Both mobile and desktop show short name (EN/FR)
            span.textContent = shortName;
        } else {
            // If no span, update entire content but preserve icon
            if (icon) {
                switcher.innerHTML = icon.outerHTML + ' <span>' + shortName + '</span>';
            } else {
                switcher.innerHTML = '<i class="fas fa-globe"></i> <span>' + shortName + '</span>';
            }
        }
    });
}

// Initialize language on page load
function initLanguage() {
    // Get saved language or default to 'fr' (French)
    const savedLang = localStorage.getItem('skedisy-language') || 'fr';
    setLanguage(savedLang);
    
    // Use event delegation for language switchers to avoid duplicate listeners
    document.addEventListener('click', function(e) {
        const switcher = e.target.closest('.lang-switcher');
        if (switcher) {
            e.preventDefault();
            e.stopPropagation();
            const newLang = switcher.getAttribute('data-lang') || (currentLanguage === 'fr' ? 'en' : 'fr');
            if (newLang !== currentLanguage) {
                setLanguage(newLang);
            }
        }
    });
}

// Initialize when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initLanguage);
} else {
    // DOM is already ready
    initLanguage();
}

