/**
 * Copy for public web pages (salon + category) — aligné authenticité Skedisy IDF.
 */
const WEB_WHATSAPP_URL = "https://wa.me/33766160394";
const WEB_WHATSAPP_DISPLAY = "+33 7 66 16 03 94";

const COPY = {
  fr: {
    bookOnApp: "Télécharger l'app",
    bookAppointment: "Réserver",
    stickyBook: "Réserver",
    downloadAndroid: "Télécharger sur Android",
    downloadIos: "Télécharger sur iPhone",
    downloadAppCta: "Télécharger l'app",
    noAppTitle: "Vous préférez l'app ?",
    noAppDesc: "Téléchargez Skedisy gratuitement — même parcours de réservation, notifications et portefeuille.",
    idfBanner:
      "Île-de-France · Beauté afro — réservez votre créneau sur cette page ou sur l'app Skedisy (gratuite).",
    openingHours: "Horaires",
    services: "Prestations",
    products: "Produits",
    staff: "L'équipe",
    reviews: "Avis",
    closed: "Fermé",
    otherServices: "Autres prestations",
    noServices: "Aucune prestation listée pour le moment.",
    noProducts: "Aucun produit pour le moment.",
    noStaff: "Informations équipe non disponibles.",
    noReviews: "Pas encore d'avis.",
    anonymous: "Cliente",
    withExpert: "Avec",
    reviewsCount: "avis",
    moreInCategory: (n) => `+ ${n} autre(s) dans cette catégorie`,
    moreServicesApp: (n) => `+ ${n} prestation(s) supplémentaires sur l'app`,
    aboutSalon: (name) => `À propos de ${name}`,
    defaultSalonDesc: (name) =>
      `Salon de beauté afro en Île-de-France. Prestations, équipe et avis — réservez en ligne ou sur l'app Skedisy.`,
    defaultHeroTitle: (name) => name,
    bookingCardTitle: "Réserver",
    metaSalonTitle: (name) => `${name} — Salon afro en Île-de-France | Skedisy`,
    metaSalonDesc: (name) =>
      `Découvrez ${name}, salon de beauté afro en Île-de-France. Prestations, équipe et avis — réservez en ligne ou sur l'app Skedisy.`,
    metaKeywords: "salon afro, beauté afro, île-de-france, tresses, locks, réservation",
    footerTagline: "Réservation beauté afro en Île-de-France — sur le web et l'app.",
    footerAbout: "À propos",
    footerHome: "Accueil",
    footerPro: "Espace pro",
    footerLegal: "Mentions",
    footerTerms: "CGU",
    footerPrivacy: "Confidentialité",
    footerCookies: "Cookies",
    footerFollowUs: "Suivez-nous",
    qrCustomer: "App cliente",
    valuePropAfro1Title: "Salon afro en IDF",
    valuePropAfro1Desc: "Prestations pensées pour les cheveux texturés et la communauté.",
    valuePropAfro2Title: "Expertes qualifiées",
    valuePropAfro2Desc: "Tresses, locks, tissages, soins — une équipe qui connaît vos besoins.",
    valuePropAfro3Title: "Réservez en ligne",
    valuePropAfro3Desc: "Créneaux en temps réel sur le site ou l'app, confirmation par email.",
    topRated: "Bien noté",
    topRatedDesc: (r, n) => `Note ${r} — ${n} avis`,
    viewBook: "Voir & réserver",
    categoryMetaTitle: (cat) => `${cat} — Salons afro en Île-de-France | Skedisy`,
    categoryMetaDesc: (cat) =>
      `Trouvez un salon afro en Île-de-France pour ${cat}. Réservez en ligne sur skedisy.com ou sur l'app Skedisy.`,
    categoryMetaKeywords: (cat) =>
      `${cat}, salon afro, beauté afro, île-de-france, réservation`,
    categorySalons: "Salons",
    categoryRated: "Avec avis",
    discoverSalons: (cat) => `Salons afro — ${cat}`,
    categoryPageLead: (cat) =>
      `Trouvez un salon afro en Île-de-France pour ${cat}. Réservez votre créneau sur le site ou sur l'app Skedisy.`,
    searchPlaceholder: "Salon, ville ou prestation…",
    mapView: "Vue carte",
    listView: "Vue liste",
    filterBtn: "Filtrer",
    filterRating: "Note minimum",
    filterAll: "Toutes",
    filterSort: "Trier par",
    sortBest: "Meilleurs",
    sortDistance: "Distance",
    sortRating: "Note",
    sortReviews: "Avis",
    sortPrice: "Prix",
    filterPrice: "Prix (à partir de)",
    filterPriceAll: "Tous",
    filterPriceUnder50: "Moins de 50 €",
    filterPrice50to100: "50–100 €",
    filterPriceOver100: "100 € et +",
    filterAvailableToday: "Dispo aujourd’hui",
    filterServices: "Prestations",
    filterServicesAll: "Toutes les prestations",
    yourLocation: "Votre position",
    applyLocation: "OK",
    locationPlaceholder: "Paris, Seine-Saint-Denis…",
    resultsCount: (salons, reviews) => `${salons} salon${salons > 1 ? "s" : ""} · ${reviews} avis`,
    resultsInCity: (city) => `Salons trouvés dans la ville de ${city}`,
    resultsInCityTpl: "Salons trouvés dans la ville de __CITY__",
    expertAtSalonTpl: "Chez __SALON__",
    categoryExpertsTitle: "Nos expertes & experts",
    noExpertsCategory: "Aucun expert listé pour cette catégorie pour le moment.",
    expertAtSalon: (name) => `Chez ${name}`,
    noSalonsCategory: "Aucun salon trouvé pour cette recherche.",
    noSalonsSearch: "Aucun salon trouvé. Essayez une autre recherche.",
    kmAway: (km) => `à ${km} km`,
    noImage: "Pas d'image",
    nextAvailable: "Prochain",
    noShowPolicyTitle: "Politique d’annulation / no-show",
    freeCancelHint: "Annulation gratuite jusqu’à __H__ h avant le RDV",
    lateCancelHint: "Annulation tardive : __P__ % de l’acompte retenu",
    noShowHint: "No-show : __P__ % du prix",
    serviceIncludesTitle: "Cette prestation comprend",
    servicePrepTitle: "Avant votre rendez-vous",
    servicePrepMust: "Vous devez arriver avec :",
    servicePrepAvoid: "À éviter :",
    serviceInspirationTitle: "Inspiration",
    serviceInspirationHint: "Ajoutez une photo si vous souhaitez reproduire un modèle.",
    serviceAddonsTitle: "Options",
    serviceDurationTitle: "Durée",
    servicePriceTitle: "Prix",
    serviceDepositTitle: "Acompte",
    serviceImportantTitle: "Important",
    serviceSeeDetails: "Voir le détail",
    serviceHideDetails: "Réduire",
    appBannerTitle: "Réserver sur Skedisy",
    appBannerDesc: "Choisissez prestations, experte et créneau sur le site — ou téléchargez l'app gratuite.",
    bookNow: "Réserver",
    messageSalon: "Message",
    callSalon: "Appeler",
    instagramSalon: "Instagram",
    messageUrgentHint: "Question urgente ? Appelez le numéro affiché sur la fiche.",
    messageLoginHint: "Connectez-vous pour envoyer un message au salon.",
    messagePlaceholder: "Votre message ou question…",
    messageSend: "Envoyer",
    messageAddPhoto: "Photo d'inspiration",
    messageEmpty: "Aucun message pour l'instant. Posez votre question ou envoyez une photo.",
    messageTitle: "Messagerie",
    messageSending: "Envoi…",
    messageError: "Impossible d'envoyer le message.",
    lateArrivalHint: "Retard toléré : __M__ min",
    policyAcceptLabel: "J’ai lu et j’accepte la politique d’annulation / no-show du salon.",
    policyAcceptRequired: "Veuillez accepter la politique du salon pour confirmer.",
    afroAddonsTitle: "Options (add-ons)",
    allCategoriesTab: "Tous",
    salonExpertsTitle: "Notre équipe",
    selectServices: "Choisir les prestations",
    selectExpert: "Choisir votre experte",
    selectDateTime: "Date et heure",
    selectDate: "Date",
    availableSlots: "Créneaux disponibles",
    monthPrev: "Mois précédent",
    monthNext: "Mois suivant",
    yourDetails: "Vos coordonnées",
    confirmBooking: "Confirmer la réservation",
    payAtSalon: "Paiement au salon",
    payWithStripe: "Payer par carte (Stripe)",
    payWithWallet: "Mon portefeuille",
    payWithWalletBalance: "Mon portefeuille (__BALANCE__)",
    walletInsufficient:
      "Solde portefeuille insuffisant. Rechargez via l'app Skedisy ou choisissez un autre mode de paiement.",
    paymentTitle: "Paiement",
    couponCode: "Code promo",
    applyCoupon: "Appliquer",
    removeCoupon: "Retirer",
    couponApplied: "Code appliqué",
    subtotal: "Sous-total",
    taxLabel: "TVA",
    discount: "Réduction",
    totalLabel: "Total",
    selectPayment: "Mode de paiement",
    stripeSecure: "Paiement sécurisé par Stripe",
    bookingSuccess: "Réservation enregistrée. Un email de confirmation vous a été envoyé.",
    bookingCancelEmailHint:
      "Un email de confirmation vous a été envoyé — vous pouvez y annuler si besoin.",
    min: "min",
    continue: "Continuer",
    back: "Retour",
    enterCouponCode: "Saisissez un code promo.",
    couponInvalid: "Code invalide",
    couponPlaceholder: "Ex. SKEDISY10",
    missingFields: "Informations manquantes : __LIST__.",
    stripeUnavailable: "Paiement Stripe indisponible",
    stripeNotLoaded: "Stripe non disponible.",
    stripeEnterCard: "Saisissez vos informations de carte, puis confirmez à nouveau.",
    paymentCancelled: "Paiement annulé",
    selectOneService: "Choisissez au moins une prestation.",
    servicesMultiHint: "Vous pouvez sélectionner plusieurs prestations (comme sur l'app). Touchez à nouveau pour retirer.",
    serviceTapToSelect: "Sélectionner",
    serviceTapToDeselect: "Désélectionner",
    bookNowWithCount: "Réserver ({n})",
    expertPreselectedHint: "Avec __NAME__ — choisissez une ou plusieurs prestations, puis continuez.",
    addOrChangeServices: "Ajouter ou modifier les prestations",
    servicesSelectedCount: "{n} prestation(s) sélectionnée(s)",
    noExpertForService: "Aucun expert pour cette prestation.",
    dateLabel: "Date",
    loading: "Chargement…",
    slotsClosed: "Fermé ou indisponible ce jour.",
    slotMorning: "Matin",
    slotAfternoon: "Après-midi",
    emailLabel: "Email",
    phoneLabel: "Téléphone",
    otpLabel: "Code reçu par email",
    otpPlaceholder: "6 chiffres",
    sendOtp: "Envoyer le code",
    otpSent: "Code envoyé",
    genericError: "Erreur",
    emailPhoneRequired: "Email et téléphone sont requis.",
    enterOtp: "Saisissez le code reçu par email.",
    verifyFailed: "Vérification échouée",
    sessionExpired: "Session expirée. Recommencez la vérification email.",
    bookingFailed: "Réservation impossible",
    missingFieldAccount: "compte",
    missingFieldExpert: "experte",
    missingFieldSalon: "salon",
    missingFieldService: "prestation",
    missingFieldDate: "date",
    missingFieldSlot: "créneau",
    missingFieldAmount: "montant",
    missingFieldAmountTtc: "montant TTC",
    missingFieldPlace: "lieu",
    slotBusy: "Un ou plusieurs créneaux de cette plage ne sont plus disponibles.",
    slotInvalid: "Impossible de réserver ce créneau pour la durée de la prestation.",
    slotSelectedRange: "Créneau",
    noticeContinue: "Continuer",
    bookAsGuest: "Réserver en tant qu'invité",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    authSignInLink: "Se connecter",
    authOr: "ou",
    authSignUpLink: "S'inscrire",
    connectedAs: "Connecté en tant que",
    authUseOtherAccount: "Utiliser un autre compte",
    afroProjectBadge: "",
    afroFromPrice: "à partir de",
    afroDurationHint: "",
    afroConfigTitle: "Quelques précisions",
    afroConfigHint: "Pour __NAME__ — afin d’afficher le bon prix et la bonne durée.",
    afroPrecisionChoiceTitle: "Préciser la coiffure ?",
    afroPrecisionChoiceHint:
      "Optionnel — utile pour un prix et une durée plus justes (longueur, nattes, mèches…).",
    afroPrecisionAdd: "Ajouter des précisions",
    afroPrecisionSkip: "Continuer sans préciser",
    afroSeeQuote: "Continuer",
    afroQuoteTitle: "Récapitulatif",
    afroQuoteHint: "Prix et durée mis à jour selon vos réponses — vous continuez la réservation.",
    afroQuoteLocked: "Prix & durée",
    afroEstimatedDuration: "Durée",
    afroDeposit: "Acompte",
    afroBalanceDue: "Reste au salon",
    afroAcceptQuote: "",
    afroReviewTitle: "Presque prêt",
    afroReviewHint:
      "Le salon pourra confirmer ou vous poser une question si besoin. Vous pouvez continuer.",
    afroClose: "Fermer",
    afroPhotoLabel: "Photo d’inspiration",
    afroPhotoOptional: "Photo d’inspiration (optionnel)",
    afroPhotoHint: "Choisissez une image depuis votre téléphone (jpg, png, webp — max 8 Mo).",
    afroPhotoRequired: "Ajoutez une photo d’inspiration pour aider le salon.",
    afroPhotoUploading: "Envoi de la photo…",
    afroPhotoUploadFailed: "Impossible d’envoyer la photo. Réessayez.",
    afroDepositPayHint: "Acompte par carte maintenant — le reste se règle au salon.",
    afroDepositStripeHint: "Paiement sécurisé de l’acompte",
    afroConfirmWithDeposit: "Payer l’acompte (__AMOUNT__) et confirmer",
    afroCancelPolicyHint: "En cas d’annulation tardive, l’acompte peut être conservé selon la politique du salon.",
    afroPrepTitle: "Pour bien préparer votre rendez-vous",
    afroPrep1: "Arrivez à l’heure (prestation longue).",
    afroPrep2: "Préparez mèches / produits si convenu.",
    afroPrep3: "Un rappel SMS vous sera envoyé avant le RDV.",
    afroServiceInfoDuration: "Environ __MIN__–__MAX__ min selon complexité",
    afroContinuePending: "Continuer",
    afroConfirmUnified:
      "Réservation enregistrée. Le détail prix et durée est inclus dans cette confirmation.",
    manageReschedule: "Modifier le créneau",
    manageCancel: "Annuler",
    manageCancelConfirm: "Confirmer l’annulation de cette réservation ?",
    manageRescheduleConfirm: "Confirmer le nouveau créneau",
    manageRescheduleLead: "Choisissez un nouveau créneau",
    upcomingTitle: "Vos prochains rendez-vous",
    bookNewSlot: "Réserver un nouveau créneau",
    authLoginTitle: "Connexion",
    authSignupTitle: "Créer un compte",
    authLoginLead: "Connectez-vous pour finaliser votre réservation sur Skedisy.",
    authSignupLead: "Quelques informations pour réserver — comme sur l'app Skedisy.",
    authPassword: "Mot de passe",
    authFirstName: "Prénom",
    authLastName: "Nom",
    authSignIn: "Se connecter",
    authCreateAccount: "Créer mon compte",
    authNoAccount: "Pas encore de compte ?",
    authHasAccount: "Déjà un compte ?",
    authBackToBooking: "← Retour à la réservation",
    authSalonPro: "Vous êtes un professionnel ? Espace pro",
    authSigningIn: "Connexion…",
    authCreatingAccount: "Création…",
    authSuccessLogin: "Connexion réussie. Reprise de votre réservation…",
    authSuccessSignup: "Compte créé. Reprise de votre réservation…",
    headerLogin: "Connexion",
    productBuyNow: "Commander",
    productOutOfStock: "Rupture de stock",
    productQuantity: "Quantité",
    productShipping: "Livraison",
    productSelectAttribute: "Choisir",
    productSelectAllAttributes: "Veuillez choisir toutes les options du produit.",
    productDeliveryTitle: "Adresse de livraison",
    productDeliveryHint: "Où souhaitez-vous recevoir votre commande ?",
    productAddressName: "Nom complet",
    productAddressLine: "Adresse",
    productAddressCity: "Ville",
    productAddressState: "Région",
    productAddressZip: "Code postal",
    productAddressCountry: "Pays",
    productUseAddress: "Utiliser cette adresse",
    productAddAddress: "Ajouter une adresse",
    productOrderTitle: "Paiement",
    productOrderConfirm: "Confirmer la commande",
    productOrderSuccess: "Commande enregistrée. Vous recevrez une confirmation par email.",
    productOrderFailed: "Commande impossible",
    productStepProduct: "Produit",
    productStepDelivery: "Livraison",
    productStepPayment: "Paiement",
    productStepDone: "Confirmé",
    productOrderSuccessTitle: "Commande confirmée",
    productWalletTopUp: "Rechargez votre portefeuille sur l'app Skedisy ou choisissez un autre moyen de paiement.",
    productWalletDisabled: "Paiement portefeuille indisponible sur le web. Utilisez l'app Skedisy.",
    productLoading: "Chargement…",
    productDescription: "Description",
    authBackToProduct: "← Retour au produit",
    authSuccessLoginProduct: "Connexion réussie. Reprise de votre commande…",
    authSuccessSignupProduct: "Compte créé. Reprise de votre commande…",
  },
  en: {
    bookOnApp: "Download the app",
    bookAppointment: "Book",
    stickyBook: "Book",
    downloadAndroid: "Download on Android",
    downloadIos: "Download on iPhone",
    downloadAppCta: "Download the app",
    noAppTitle: "Prefer the app?",
    noAppDesc: "Download Skedisy for free — same booking flow, plus notifications and wallet.",
    idfBanner:
      "Île-de-France · Afro beauty — book your slot on this page or on the free Skedisy app.",
    openingHours: "Opening hours",
    services: "Services",
    products: "Products",
    staff: "Team",
    reviews: "Reviews",
    closed: "Closed",
    otherServices: "Other services",
    noServices: "No services listed yet.",
    noProducts: "No products yet.",
    noStaff: "Team information not available.",
    noReviews: "No reviews yet.",
    anonymous: "Client",
    withExpert: "With",
    reviewsCount: "reviews",
    moreInCategory: (n) => `+ ${n} more in this category`,
    moreServicesApp: (n) => `+ ${n} more services on the app`,
    aboutSalon: (name) => `About ${name}`,
    defaultSalonDesc: (name) =>
      `Afro beauty salon in Île-de-France. Services, team and reviews — book online or on the Skedisy app.`,
    defaultHeroTitle: (name) => name,
    bookingCardTitle: "Book",
    metaSalonTitle: (name) => `${name} — Afro salon in Île-de-France | Skedisy`,
    metaSalonDesc: (name) =>
      `Discover ${name}, an Afro beauty salon in Île-de-France. Services, team and reviews — book online or on the Skedisy app.`,
    metaKeywords: "afro salon, afro beauty, ile-de-france, braids, locs, booking",
    footerTagline: "Afro beauty booking in Île-de-France — on the web and the app.",
    footerAbout: "About",
    footerHome: "Home",
    footerPro: "For professionals",
    footerLegal: "Legal",
    footerTerms: "Terms",
    footerPrivacy: "Privacy",
    footerCookies: "Cookies",
    footerFollowUs: "Follow us",
    qrCustomer: "Customer app",
    valuePropAfro1Title: "Afro salon in IDF",
    valuePropAfro1Desc: "Services for textured hair and our community.",
    valuePropAfro2Title: "Skilled stylists",
    valuePropAfro2Desc: "Braids, locs, weaves, treatments — experts who understand your hair.",
    valuePropAfro3Title: "Book online",
    valuePropAfro3Desc: "Real-time slots on the website or app, email confirmation.",
    topRated: "Top rated",
    topRatedDesc: (r, n) => `Rated ${r} by ${n} clients`,
    viewBook: "View & book",
    categoryMetaTitle: (cat) => `${cat} — Afro salons in Île-de-France | Skedisy`,
    categoryMetaDesc: (cat) =>
      `Find an Afro salon in Île-de-France for ${cat}. Book online on skedisy.com or on the Skedisy app.`,
    categoryMetaKeywords: (cat) =>
      `${cat}, afro salon, afro beauty, ile-de-france, booking`,
    categorySalons: "Salons",
    categoryRated: "Rated",
    discoverSalons: (cat) => `Afro salons — ${cat}`,
    categoryPageLead: (cat) =>
      `Find an Afro salon in Île-de-France for ${cat}. Book your slot on the website or on the Skedisy app.`,
    searchPlaceholder: "Salon, city or service…",
    mapView: "Map view",
    listView: "List view",
    filterBtn: "Filter",
    filterRating: "Minimum rating",
    filterAll: "All",
    filterSort: "Sort by",
    sortBest: "Best",
    sortDistance: "Distance",
    sortRating: "Rating",
    sortReviews: "Reviews",
    sortPrice: "Price",
    filterPrice: "Price (from)",
    filterPriceAll: "Any",
    filterPriceUnder50: "Under €50",
    filterPrice50to100: "€50–100",
    filterPriceOver100: "€100+",
    filterAvailableToday: "Available today",
    filterServices: "Services",
    filterServicesAll: "All services",
    yourLocation: "Your location",
    applyLocation: "OK",
    locationPlaceholder: "Paris, Seine-Saint-Denis…",
    resultsCount: (salons, reviews) => `${salons} salon${salons !== 1 ? "s" : ""} · ${reviews} reviews`,
    resultsInCity: (city) => `Salons found in ${city}`,
    resultsInCityTpl: "Salons found in __CITY__",
    expertAtSalonTpl: "At __SALON__",
    categoryExpertsTitle: "Our stylists & experts",
    noExpertsCategory: "No experts listed for this category yet.",
    expertAtSalon: (name) => `At ${name}`,
    noSalonsCategory: "No salons found for this search.",
    noSalonsSearch: "No salons found. Try a different search.",
    kmAway: (km) => `${km} km away`,
    noImage: "No image",
    nextAvailable: "Next",
    noShowPolicyTitle: "No-Show / Late Cancellation Policy",
    freeCancelHint: "Free cancellation until __H__h before the appointment",
    lateCancelHint: "Late cancellation: __P__% of the deposit retained",
    noShowHint: "No-show: __P__% of the price",
    serviceIncludesTitle: "This service includes",
    servicePrepTitle: "Before your appointment",
    servicePrepMust: "Please arrive with:",
    servicePrepAvoid: "Please avoid:",
    serviceInspirationTitle: "Inspiration",
    serviceInspirationHint: "Add a photo if you want to match a specific look.",
    serviceAddonsTitle: "Options",
    serviceDurationTitle: "Duration",
    servicePriceTitle: "Price",
    serviceDepositTitle: "Deposit",
    serviceImportantTitle: "Important",
    serviceSeeDetails: "See details",
    serviceHideDetails: "Hide",
    appBannerTitle: "Book on Skedisy",
    appBannerDesc: "Pick services, stylist and time slot on the website — or download the free app.",
    bookNow: "Book",
    messageSalon: "Message",
    callSalon: "Call",
    instagramSalon: "Instagram",
    messageUrgentHint: "Urgent question? Call the number on the profile.",
    messageLoginHint: "Sign in to message the salon.",
    messagePlaceholder: "Your message or question…",
    messageSend: "Send",
    messageAddPhoto: "Inspiration photo",
    messageEmpty: "No messages yet. Ask a question or send a photo.",
    messageTitle: "Messages",
    messageSending: "Sending…",
    messageError: "Could not send message.",
    lateArrivalHint: "Late arrival tolerance: __M__ min",
    policyAcceptLabel: "I have read and accept the salon’s cancellation / no-show policy.",
    policyAcceptRequired: "Please accept the salon policy to confirm.",
    afroAddonsTitle: "Options (add-ons)",
    allCategoriesTab: "All",
    salonExpertsTitle: "Our team",
    selectServices: "Choose services",
    selectExpert: "Choose your stylist",
    selectDateTime: "Date & time",
    selectDate: "Date",
    availableSlots: "Available slots",
    monthPrev: "Previous month",
    monthNext: "Next month",
    yourDetails: "Your details",
    confirmBooking: "Confirm booking",
    payAtSalon: "Pay at the salon",
    payWithStripe: "Pay by card (Stripe)",
    payWithWallet: "My wallet",
    payWithWalletBalance: "My wallet (__BALANCE__)",
    walletInsufficient:
      "Insufficient wallet balance. Top up in the Skedisy app or choose another payment method.",
    paymentTitle: "Payment",
    couponCode: "Promo code",
    applyCoupon: "Apply",
    removeCoupon: "Remove",
    couponApplied: "Code applied",
    subtotal: "Subtotal",
    taxLabel: "Tax",
    discount: "Discount",
    totalLabel: "Total",
    selectPayment: "Payment method",
    stripeSecure: "Secure payment by Stripe",
    bookingSuccess: "Booking saved. A confirmation email has been sent.",
    bookingCancelEmailHint:
      "A confirmation email was sent — you can cancel from that email if needed.",
    min: "min",
    continue: "Continue",
    back: "Back",
    enterCouponCode: "Enter a promo code.",
    couponInvalid: "Invalid code",
    couponPlaceholder: "e.g. SKEDISY10",
    missingFields: "Missing information: __LIST__.",
    stripeUnavailable: "Stripe payment unavailable",
    stripeNotLoaded: "Stripe is not available.",
    stripeEnterCard: "Enter your card details, then confirm again.",
    paymentCancelled: "Payment cancelled",
    selectOneService: "Please choose at least one service.",
    servicesMultiHint: "You can select multiple services (same as the app). Tap again to remove.",
    serviceTapToSelect: "Select",
    serviceTapToDeselect: "Deselect",
    bookNowWithCount: "Book ({n})",
    expertPreselectedHint: "With __NAME__ — choose one or more services, then continue.",
    addOrChangeServices: "Add or change services",
    servicesSelectedCount: "{n} service(s) selected",
    noExpertForService: "No stylist available for this service.",
    dateLabel: "Date",
    loading: "Loading…",
    slotsClosed: "Closed or unavailable on this day.",
    slotMorning: "Morning",
    slotAfternoon: "Afternoon",
    emailLabel: "Email",
    phoneLabel: "Phone",
    otpLabel: "Code from email",
    otpPlaceholder: "6 digits",
    sendOtp: "Send code",
    otpSent: "Code sent",
    genericError: "Error",
    emailPhoneRequired: "Email and phone are required.",
    enterOtp: "Enter the code from your email.",
    verifyFailed: "Verification failed",
    sessionExpired: "Session expired. Please verify your email again.",
    bookingFailed: "Unable to complete booking",
    missingFieldAccount: "account",
    missingFieldExpert: "stylist",
    missingFieldSalon: "salon",
    missingFieldService: "service",
    missingFieldDate: "date",
    missingFieldSlot: "time slot",
    missingFieldAmount: "amount",
    missingFieldAmountTtc: "total amount",
    missingFieldPlace: "location",
    slotBusy: "One or more time slots in this range are no longer available.",
    slotInvalid: "This time cannot be booked for the selected service duration.",
    slotSelectedRange: "Time slot",
    noticeContinue: "Continue",
    bookAsGuest: "Book as a guest",
    alreadyHaveAccount: "Already have an account?",
    authSignInLink: "Sign in",
    authOr: "or",
    authSignUpLink: "Sign up",
    connectedAs: "Signed in as",
    authUseOtherAccount: "Use another account",
    afroProjectBadge: "",
    afroFromPrice: "from",
    afroDurationHint: "",
    afroConfigTitle: "A few details",
    afroConfigHint: "For __NAME__ — so we can show the right price and duration.",
    afroPrecisionChoiceTitle: "Add hair details?",
    afroPrecisionChoiceHint:
      "Optional — helps show a fairer price and duration (length, braid size, hair…).",
    afroPrecisionAdd: "Add details",
    afroPrecisionSkip: "Continue without details",
    afroSeeQuote: "Continue",
    afroQuoteTitle: "Summary",
    afroQuoteHint: "Price and duration updated from your answers — continue booking.",
    afroQuoteLocked: "Price & duration",
    afroEstimatedDuration: "Duration",
    afroDeposit: "Deposit",
    afroBalanceDue: "Balance at salon",
    afroAcceptQuote: "",
    afroReviewTitle: "Almost ready",
    afroReviewHint:
      "The salon may confirm or ask a question if needed. You can continue.",
    afroClose: "Close",
    afroPhotoLabel: "Inspiration photo",
    afroPhotoOptional: "Inspiration photo (optional)",
    afroPhotoHint: "Choose an image from your phone (jpg, png, webp — max 8 MB).",
    afroPhotoRequired: "Add an inspiration photo to help the salon.",
    afroPhotoUploading: "Uploading photo…",
    afroPhotoUploadFailed: "Could not upload the photo. Try again.",
    afroDepositPayHint: "Card deposit now — pay the balance at the salon.",
    afroDepositStripeHint: "Secure deposit payment",
    afroConfirmWithDeposit: "Pay deposit (__AMOUNT__) and confirm",
    afroCancelPolicyHint: "Late cancellations may forfeit the deposit per salon policy.",
    afroPrepTitle: "Prepare for your appointment",
    afroPrep1: "Arrive on time (long service).",
    afroPrep2: "Bring hair / products if agreed.",
    afroPrep3: "You will get an SMS reminder before the visit.",
    afroServiceInfoDuration: "About __MIN__–__MAX__ min depending on complexity",
    afroContinuePending: "Continue",
    afroConfirmUnified:
      "Booking saved. Price and duration details are included in this confirmation.",
    manageReschedule: "Change time slot",
    manageCancel: "Cancel",
    manageCancelConfirm: "Confirm cancellation of this booking?",
    manageRescheduleConfirm: "Confirm new time slot",
    manageRescheduleLead: "Choose a new time slot",
    upcomingTitle: "Your upcoming appointments",
    bookNewSlot: "Book a new slot",
    authLoginTitle: "Sign in",
    authSignupTitle: "Create an account",
    authLoginLead: "Sign in to complete your booking on Skedisy.",
    authSignupLead: "A few details to book — same as on the Skedisy app.",
    authPassword: "Password",
    authFirstName: "First name",
    authLastName: "Last name",
    authSignIn: "Sign in",
    authCreateAccount: "Create my account",
    authNoAccount: "No account yet?",
    authHasAccount: "Already have an account?",
    authBackToBooking: "← Back to booking",
    authSalonPro: "Salon professional? Pro area",
    authSigningIn: "Signing in…",
    authCreatingAccount: "Creating account…",
    authSuccessLogin: "Signed in. Resuming your booking…",
    authSuccessSignup: "Account created. Resuming your booking…",
    headerLogin: "Sign in",
    productBuyNow: "Buy now",
    productOutOfStock: "Out of stock",
    productQuantity: "Quantity",
    productShipping: "Shipping",
    productSelectAttribute: "Choose",
    productSelectAllAttributes: "Please choose all product options.",
    productDeliveryTitle: "Delivery address",
    productDeliveryHint: "Where should we deliver your order?",
    productAddressName: "Full name",
    productAddressLine: "Address",
    productAddressCity: "City",
    productAddressState: "State / region",
    productAddressZip: "Postal code",
    productAddressCountry: "Country",
    productUseAddress: "Use this address",
    productAddAddress: "Add address",
    productOrderTitle: "Payment",
    productOrderConfirm: "Confirm order",
    productOrderSuccess: "Order placed. You will receive a confirmation email.",
    productOrderFailed: "Unable to place order",
    productStepProduct: "Product",
    productStepDelivery: "Delivery",
    productStepPayment: "Payment",
    productStepDone: "Confirmed",
    productOrderSuccessTitle: "Order confirmed",
    productWalletTopUp: "Top up your wallet in the Skedisy app or choose another payment method.",
    productWalletDisabled: "Wallet payment is not available on the web. Use the Skedisy app.",
    productLoading: "Loading…",
    productDescription: "Description",
    authBackToProduct: "← Back to product",
    authSuccessLoginProduct: "Signed in. Resuming your order…",
    authSuccessSignupProduct: "Account created. Resuming your order…",
  },
};

function resolveLang(queryLang) {
  const raw = (queryLang || "fr").toString().toLowerCase();
  return raw.startsWith("en") ? "en" : "fr";
}

function getWebCopy(lang) {
  const code = lang === "en" ? "en" : "fr";
  return COPY[code];
}

const WEEKDAY_FR = {
  Monday: "Lundi",
  Tuesday: "Mardi",
  Wednesday: "Mercredi",
  Thursday: "Jeudi",
  Friday: "Vendredi",
  Saturday: "Samedi",
  Sunday: "Dimanche",
};

function parseSalonTimeString(timeStr) {
  const s = (timeStr || "").trim();
  if (!s) return null;
  const m24 = s.match(/^(\d{1,2}):(\d{2})$/);
  if (m24) {
    return { h: parseInt(m24[1], 10), m: parseInt(m24[2], 10) };
  }
  const m12 = s.match(/^(\d{1,2}):(\d{2})\s*(AM|PM)$/i);
  if (m12) {
    let h = parseInt(m12[1], 10);
    const m = parseInt(m12[2], 10);
    const ampm = m12[3].toUpperCase();
    if (ampm === "PM" && h !== 12) h += 12;
    if (ampm === "AM" && h === 12) h = 0;
    return { h, m };
  }
  return null;
}

function formatSalonTimeForDisplay(timeStr, lang) {
  const parsed = parseSalonTimeString(timeStr);
  if (!parsed) return (timeStr || "").trim() || "—";
  if (lang === "fr") {
    return `${String(parsed.h).padStart(2, "0")}h${String(parsed.m).padStart(2, "0")}`;
  }
  const ampm = parsed.h >= 12 ? "PM" : "AM";
  let h12 = parsed.h % 12;
  if (h12 === 0) h12 = 12;
  return `${String(h12).padStart(2, "0")}:${String(parsed.m).padStart(2, "0")} ${ampm}`;
}

function formatSalonDayName(day, lang) {
  if (!day) return "—";
  if (lang === "fr") return WEEKDAY_FR[day] || day;
  return day;
}

function formatSalonHoursItemHtml(time, lang, copy) {
  const dayLabel = formatSalonDayName(time.day, lang);
  const isClosed =
    !time.isActive || (time.openTime === "" && time.closedTime === "");
  if (isClosed) {
    return `<div class="hours-item"><span class="hours-day">${dayLabel}</span><span class="hours-time hours-closed">${copy.closed}</span></div>`;
  }
  const open = formatSalonTimeForDisplay(time.openTime, lang);
  const close = formatSalonTimeForDisplay(time.closedTime, lang);
  const range = `${open} - ${close}`;
  return `<div class="hours-item"><span class="hours-day">${dayLabel}</span><span class="hours-time">${range}</span></div>`;
}

function idfBannerHtml(copy) {
  return `<div class="skedisy-idf-banner" role="note"><p>${copy.idfBanner}</p></div>`;
}

function skedisyFooterHtml(baseURL, copy) {
  return `
    <footer class="footer sq-footer">
        <div class="container">
            <div class="footer-content">
                <div class="footer-section">
                    <h3>Skedisy</h3>
                    <p>${copy.footerTagline}</p>
                    <div class="contact-info">
                        <p><i class="fas fa-envelope"></i> support@skedisy.com</p>
                        <p><a href="${WEB_WHATSAPP_URL}" target="_blank" rel="noopener noreferrer"><i class="fab fa-whatsapp"></i> WhatsApp · ${WEB_WHATSAPP_DISPLAY}</a></p>
                    </div>
                    <div class="footer-social">
                        <h4>${copy.footerFollowUs}</h4>
                        <div class="footer-social-links">
                            <a href="https://www.facebook.com/profile.php?id=61586655939283" class="footer-social-link" target="_blank" rel="noopener noreferrer" aria-label="Skedisy sur Facebook"><i class="fab fa-facebook-f" aria-hidden="true"></i></a>
                            <a href="https://www.instagram.com/skedisy/" class="footer-social-link" target="_blank" rel="noopener noreferrer" aria-label="Skedisy sur Instagram"><i class="fab fa-instagram" aria-hidden="true"></i></a>
                            <a href="https://www.tiktok.com/@skedisy" class="footer-social-link" target="_blank" rel="noopener noreferrer" aria-label="Skedisy sur TikTok"><i class="fab fa-tiktok" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
                <div class="footer-section">
                    <h4>${copy.footerAbout}</h4>
                    <ul>
                        <li><a href="${baseURL}/">${copy.footerHome}</a></li>
                        <li><a href="${baseURL}/professionnel/">${copy.footerPro}</a></li>
                    </ul>
                </div>
                <div class="footer-section">
                    <h4>${copy.footerLegal}</h4>
                    <ul>
                        <li><a href="${baseURL}/terms/">${copy.footerTerms}</a></li>
                        <li><a href="${baseURL}/privacy/">${copy.footerPrivacy}</a></li>
                        <li><a href="${baseURL}/cookies/">${copy.footerCookies}</a></li>
                    </ul>
                </div>
            </div>
            <div class="footer-bottom">
                <p>&copy; ${new Date().getFullYear()} Skedisy. All rights reserved.</p>
            </div>
        </div>
    </footer>`;
}

module.exports = {
  WEB_WHATSAPP_URL,
  WEB_WHATSAPP_DISPLAY,
  getWebCopy,
  resolveLang,
  idfBannerHtml,
  skedisyFooterHtml,
  formatSalonHoursItemHtml,
};
