/** Aligné AUTHENTICITE_SKEDISY — console admin Skedisy. */
export const SKEDISY_ADMIN_PORTAL_COPY = {
  kicker: "Skedisy",
  welcome: "Administration",
  loginTitle: "Connexion",
  loginSubtitle: "Identifiants administrateur.",
  loginHint: "",
  signUpTitle: "Créer l'accès",
  signUpSubtitle: "Inscription administrateur avec code.",
  signUpHint: "Email, mot de passe et code.",
  submitLogin: "Se connecter",
  submitSignUp: "Créer le compte",
  email: "Email",
  password: "Mot de passe",
  confirmPassword: "Confirmer le mot de passe",
  code: "Code",
  errEmail: "L'email est requis.",
  errPassword: "Le mot de passe est requis.",
  errConfirmPassword: "La confirmation est requise.",
  errPasswordMismatch: "Les mots de passe ne correspondent pas.",
  errCode: "Le code est requis.",
  footerLink: "Découvrir skedisy.com",
  updateCodeTitle: "Mettre à jour le code",
  updateCodeSubtitle: "Nouveau code administrateur.",
  updateCodeHint: "Email, mot de passe et nouveau code.",
  submitUpdateCode: "Enregistrer",
  profileTitle: "Profil administrateur",
  uploadImage: "Changer la photo",
  editProfile: "Modifier le profil",
  changePassword: "Changer le mot de passe",
  passwordSettings: "Mot de passe",
  oldPassword: "Mot de passe actuel",
  newPassword: "Nouveau mot de passe",
  confirmPasswordField: "Confirmer le mot de passe",
  nameLabel: "Nom",
  emailLabel: "Email",
  newPasswordRequired: "Le nouveau mot de passe est requis.",
  confirmPasswordRequired: "La confirmation est requise.",
  passwordMismatch: "Les mots de passe ne correspondent pas.",
  oldPasswordRequired: "Le mot de passe actuel est requis.",
  nameRequired: "Le nom est requis.",
  emailRequired: "L'email est requis.",
  imageRequired: "La photo est requise.",
};
