/**
 * Copy interface Skedisy — console admin.
 */
export const SKEDISY_ADMIN_UI = {
  brand: "Skedisy",
  roleAdmin: "Admin",
  loading: "Chargement…",
  breadcrumbHome: "Tableau de bord",
  nav: {
    menu: "Menu",
    user: "Utilisateurs",
    services: "Prestations",
    ecommerce: "Boutique",
    orders: "Commandes",
    bookings: "Réservations",
    finance: "Finances",
    report: "Rapports",
    dashboard: "Tableau de bord",
    salons: "Salons",
    experts: "Coiffeur·se·s / pros",
    customers: "Clientes",
    reviews: "Avis",
    complaints: "Réclamations",
    attendance: "Présences",
    withdrawRequest: "Demandes de retrait",
    product: "Produit",
    productCategory: "Catégories produits",
    productRequest: "Demandes produit",
    order: "Commandes",
    category: "Catégories",
    userRecharge: "Rechargements",
    expertEarnings: "Gains pros",
    coupon: "Codes promo",
    salonPayment: "Paiements salons",
    expertPayments: "Paiements experts",
    expertWithdrawHistory: "Historique retraits pros",
    salonHoliday: "Congés salons",
    salonRequest: "Demandes salon",
    setting: "Paramètres",
    logout: "Déconnexion",
    allBookings: "Toutes les réservations",
    dailyBookings: "Réservations du jour",
    monthlyReport: "Rapport mensuel",
    teamCalendar: "Planning équipe",
    staffAttendance: "Présences équipe",
    pending: "En attente",
    approved: "Validées",
    rejected: "Refusées",
  },
  dashboard: {
    title: "Vue d'ensemble",
    welcome: "Bon retour, équipe Skedisy",
    totalCustomers: "Clientes",
    completedBooking: "Réservations terminées",
    totalSalons: "Salons IDF",
    totalExperts: "Pros",
    salesCommission: "Commissions",
    totalRevenue: "Chiffre d'affaires",
    dataAnalysis: "Analyse",
    revenueBookingChart: "Revenus et réservations",
    topSalons: "Salons les plus actifs",
    viewAll: "Tout voir",
    todayBookings: "Réservations du jour",
    showMore: "Voir plus",
    fallbackUser: "Cliente",
  },
  table: {
    no: "N°",
    image: "Photo",
    name: "Nom",
    salonCommission: "Commission salon",
    bookings: "Réservations",
    user: "Cliente",
    salon: "Salon",
    time: "Heure",
    showMore: "Voir plus",
    expert: "Pro / coiffeur·se",
    service: "Prestation",
    bookingId: "N° réservation",
    duration: "Durée",
    date: "Date",
    status: "Statut",
    firstSlot: "Créneau",
    price: "Prix",
    adminCommission: "Commission plateforme",
    action: "Action",
    details: "Détails",
    createdAt: "Créé le",
    finalAmount: "Montant final",
    salonEarning: "Gain salon",
    email: "Email",
    mobile: "Tél.",
    claimStatus: "Réclamation fiche",
    active: "Actif",
    schedule: "Planning",
    order: "Commande",
    startTime: "Heure de début",
    srNo: "N°",
    expertImage: "Photo pro",
    salonImage: "Photo salon",
    userImage: "Photo cliente",
    expertName: "Nom du pro",
    salonName: "Nom du salon",
    userName: "Nom cliente",
    firstName: "Prénom",
    lastName: "Nom",
    info: "Infos",
    accept: "Accepter",
    reject: "Refuser",
    isActive: "Actif",
    product: "Produit",
    productCode: "Code produit",
    shipping: "Livraison",
    createStatus: "Statut création",
    orderId: "N° commande",
    userInfo: "Cliente",
    items: "Articles",
    reason: "Motif",
    day: "Jour",
    openTime: "Ouverture",
    closeTime: "Fermeture",
    closedTime: "Fermé à",
    breakStart: "Début pause",
    breakEnd: "Fin pause",
    edit: "Modifier",
    review: "Avis",
    rating: "Note",
    category: "Catégorie",
    categoryName: "Catégorie",
    present: "Présent",
    absent: "Absent",
    pay: "Payer",
    country: "Pays",
    platformFee: "Frais plateforme (%)",
    bestSeller: "Meilleures ventes",
    booking: "Réservation",
    delete: "Supprimer",
    brand: "Marque",
    mrp: "Prix public",
    outOfStock: "Rupture",
    trending: "Tendance",
    newCollection: "Nouveauté",
    block: "Bloquer",
    about: "À propos",
    commission: "Commission",
    salonCommissionPct: "Commission salon (%)",
    expertEarning: "Gains pro",
    adminEarning: "Gains plateforme",
    earning: "Gain",
    earnings: "Gains",
    earningsExpert: "Gains (pro)",
    earningsAdmin: "Gains (plateforme)",
    amount: "Montant",
    payoutMonth: "Mois de paiement",
    paymentStatus: "Statut paiement",
    settlementType: "Type règlement",
    settlementDate: "Date règlement",
    paymentDate: "Date paiement",
    totalBookings: "Total réservations",
    paidPayment: "Montant payé",
    serviceEarning: "Gains prestations",
    bonusPenalty: "Bonus / pénalité",
    settlementMonth: "Mois de règlement",
    paymentMode: "Mode de paiement",
    transactionType: "Type",
    transactionCompleted: "Terminé",
    transactionDetails: "Détail transaction",
    uniqueId: "Référence",
    credit: "Crédit",
    debit: "Débit",
    quantity: "Quantité",
    month: "Mois",
    monthYear: "Mois / année",
    note: "Note",
    notification: "Notification",
    total: "Total",
    totalExperts: "Total pros",
    totalDays: "Total jours",
    totalEarning: "Gain total",
    totalPrice: "Prix total",
    totalRevenue: "Revenu total",
    totalCompletedBookings: "Réservations terminées",
    totalPaymentToExpert: "Paiement au pro",
    noBooking: "Nb réservations",
    noExperts: "Nb pros",
    serviceAmount: "Montant prestations",
    servicesAmountPlus: "Prestations +",
    adminEarningPlus: "Gains plateforme +",
    expertEarningPlus: "Gains pro +",
    salonEarningPlus: "Gains salon +",
    taxEquals: "Taxe =",
    tax: "Taxe",
    taxPlus: "Taxe +",
    plus: "+",
    eq: "=",
    deliveredService: "Prestation réalisée",
    itemDetail: "Détail article",
    bookedAt: "Réservé le",
    cities: "Villes",
    absentDays: "Jours d'absence",
    availableDays: "Jours disponibles",
    allAttendanceInfo: "Présences",
    gender: "Genre",
    expertInfo: "Infos pro",
    title: "Titre",
    description: "Description",
    code: "Code",
    invoice: "Facture",
    discountPct: "Remise (%)",
    maxDiscount: "Remise max.",
    paymentType: "Type de paiement",
    confirm: "Confirmer",
  },
  status: {
    completed: "Terminée",
    confirm: "Confirmée",
    cancel: "Annulée",
    pending: "En attente",
  },
  actions: {
    processing: "Traitement…",
  },
  common: {
    submit: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    update: "Mettre à jour",
    back: "Retour",
    searchPlaceholder: "Rechercher…",
    paginationShow: "Afficher",
    confirm: "Confirmer",
    accept: "Accepter",
    all: "Tout",
    pending: "En attente",
    approved: "Validé",
    rejected: "Refusé",
    enterYour: "Saisir",
  },
  dialog: {
    cancelBooking: "Annuler la réservation",
    completeBooking: "Terminer la réservation",
    bookingInfo: "Détail réservation",
    reason: "Motif",
    reasonRequired: "Le motif est requis.",
    priceAboveMrp: "Le prix ne peut pas dépasser le prix public.",
    enterPrice: "Saisir le prix",
    enterName: "Nom",
    enterDetail: "Détail",
    selectServices: "Choisir les prestations",
    selectSalon: "Choisir le salon",
    selectCategory: "Choisir la catégorie",
    selectCategoryHint: "Sélectionnez une catégorie",
    selectAttribute: "Choisir un attribut",
    selectImages: "Photos (plusieurs)",
    enterDuration: "Durée (minutes)",
    firstNameRequired: "Le prénom est requis.",
    lastNameRequired: "Le nom est requis.",
    mobileRequired: "Le téléphone est requis.",
    mobileInvalid: "Le numéro doit comporter 6 à 13 chiffres.",
    emailRequired: "L'email est requis.",
    emailInvalid: "Adresse email invalide.",
    imageRequired: "La photo est requise.",
    ageRequired: "L'âge est requis.",
    ageInvalid: "Âge invalide (18–100).",
    commissionRequired: "La commission est requise.",
    commissionInvalid: "Commission invalide (0–99 %).",
    passwordRequired: "Le mot de passe est requis.",
    servicePickRequired: "Sélectionnez au moins une prestation.",
    durationInvalid: "Durée invalide.",
    priceInvalid: "Prix invalide.",
    checkInTime: "Heure d'arrivée",
    checkOutTime: "Heure de fin",
    uploadImage: "Changer la photo",
    editProfile: "Modifier le profil",
    changePassword: "Changer le mot de passe",
    passwordSettings: "Mot de passe",
    oldPasswordRequired: "Le mot de passe actuel est requis.",
    newPasswordRequired: "Le nouveau mot de passe est requis.",
    confirmPasswordRequired: "La confirmation est requise.",
    passwordMismatch: "Les mots de passe ne correspondent pas.",
    adminNameRequired: "Le nom est requis.",
    adminEmailRequired: "L'email est requis.",
    dateRequired: "La date est requise.",
    salonRequired: "Le salon est requis.",
    endDateRequired: "La date de fin est requise.",
    bankNameRequired: "Le nom de la banque est requis.",
    accountRequired: "Le numéro de compte est requis.",
    branchRequired: "L'agence est requise.",
    ifscRequired: "Le code banque est requis.",
    upiRequired: "L'identifiant UPI est requis.",
    priceRequired: "Le prix est requis.",
    productCodeRequired: "Le code produit est requis.",
    productNameRequired: "Le nom du produit est requis.",
    descriptionRequired: "La description est requise.",
    brandRequired: "La marque est requise.",
    categoryRequired: "La catégorie est requise.",
    attributeRequired: "Au moins un attribut est requis.",
    mrpRequired: "Le prix public est requis.",
    shippingRequired: "Les frais de livraison sont requis.",
    mainImageRequired: "L'image principale est requise.",
    imagesRequired: "Au moins une image est requise.",
    nameRequiredBang: "Le nom est requis.",
    imageRequiredCategory: "L'image est requise.",
    openTimeRequired: "L'heure d'ouverture est requise.",
    closeTimeRequired: "L'heure de fermeture est requise.",
    durationRequired: "La durée est requise.",
    firstNameRequired: "Le prénom est requis.",
    notificationTitleRequired: "Le titre est requis.",
    notificationMessageRequired: "Le message est requis.",
  },

  form: {
    productCode: "Code produit (6 chiffres)",
    productName: "Nom du produit",
    description: "Description",
    brand: "Marque",
    price: "Prix",
    mrp: "Prix public (MRP)",
    shippingCharges: "Frais de livraison",
    mainImage: "Photo principale",
    serviceName: "Nom de la prestation",
    serviceCharge: "Tarif prestation",
    serviceDuration: "Durée (min)",
    mobileNumber: "Téléphone",
    email: "Email",
    age: "Âge",
    adminCommissionPct: "Commission plateforme (%)",
    salonCommissionPct: "Commission salon (%)",
    bankName: "Nom de la banque",
    accountNumber: "N° de compte",
    branchName: "Agence",
    branchNameTypo: "Agence",
    ifscCode: "Code banque (IFSC)",
    upiId: "Identifiant UPI",
    password: "Mot de passe",
    male: "Homme",
    female: "Femme",
    image: "Photo",
    firstName: "Prénom",
    lastName: "Nom",
    uniqueId: "Référence",
    gender: "Genre",
    emailId: "Email",
    loginType: "Mode de connexion",
    salonName: "Nom du salon",
    platformFeePct: "Frais plateforme (%)",
    platformFeeTypo: "Frais plateforme (%)",
    shareLink: "Lien de partage",
    latitude: "Latitude",
    longitude: "Longitude",
    address: "Adresse",
    landmark: "Repère",
    landMark: "Repère",
    city: "Ville",
    state: "Région",
    country: "Pays",
    date: "Date",
    time: "Heure",
    checkOutTime: "Heure de fin",
    title: "Titre",
    message: "Message",
    details: "Détail",
    reportDateTime: "Date et heure du signalement",
    solvedDateTime: "Date et heure de résolution",
    expertCount: "Nombre de pros",
    mobile: "Téléphone",
    day: "Jour",
    slotTimeMinute: "Créneau (minutes)",
    deliveredServiceName: "Prestation réalisée",
    trackingId: "N° de suivi",
    trackingLink: "Lien de suivi",
    subTotal: "Sous-total",
    wallet: "Portefeuille",
    name: "Nom",
    about: "À propos",
  },
  bonusPenalty: {
    title: "Bonus ou pénalité",
    bonus: "Bonus",
    penalty: "Pénalité",
    note: "Note",
    hint: "Indiquez un bonus ou une pénalité (pas les deux).",
    required: "Saisissez un bonus ou une pénalité.",
  },
  complaints: {
    sourceLabel: "Source",
    clientTab: "Clientes",
    expertTab: "Experts",
    statusLabel: "Statut",
    all: "Toutes",
    pending: "En attente",
    solved: "Résolues",
    info: "Détail",
    solve: "Résoudre",
    solvedBadge: "Résolue",
    pendingBadge: "En attente",
  },

  settings: {
    privacyPolicyRequired: "Le lien politique de confidentialité est requis.",
    tncRequired: "Les CGU sont requises.",
    stripePublishableRequired: "La clé publique Stripe est requise.",
    stripeSecretRequired: "La clé secrète Stripe est requise.",
    razorIdRequired: "L'identifiant Razorpay est requis.",
    razorSecretRequired: "La clé secrète Razorpay est requise.",
    taxRequired: "La taxe est requise.",
    currencyNameRequired: "Le nom de la devise est requis.",
    currencySymbolRequired: "Le symbole devise est requis.",
    flutterWaveRequired: "La clé Flutterwave est requise.",
    firebaseRequired: "La clé Firebase est requise.",
    adminCommissionRequired: "La commission admin (produits) est requise.",
    customerCommissionRequired: "La commission cliente est requise.",
    salonCommissionRequired: "La commission salon est requise.",
    cancelOrderRequired: "Les frais d'annulation commande sont requis.",
    minWithdrawRequired: "Le montant minimum de retrait est requis.",
    minWalletRequired: "Le solde minimum portefeuille salon est requis.",
    stripePublishablePh: "Clé publique Stripe",
    stripeSecretPh: "Clé secrète Stripe",
    mtnSubscriptionPh: "Clé d'abonnement MTN MoMo",
    mtnApiUserPh: "API User ID MTN MoMo (UUID)",
    mtnApiKeyPh: "Clé API MTN MoMo",
    mtnCallbackPh: "Hôte de callback (ex. skedisy.com)",
    razorSecretPh: "Clé secrète Razorpay",
    razorIdPh: "Identifiant Razorpay",
    privacyPolicyPh: "Lien politique de confidentialité",
    tncPh: "Conditions générales (CGU)",
    taxPh: "Taxe (%)",
    cancelOrderPh: "Frais annulation commande",
    adminCommissionPh: "Commission admin (produits)",
    customerCommissionPh: "Commission cliente",
    salonCommissionPh: "Commission salon",
    minWalletPh: "Solde minimum portefeuille salon",
    currencyNamePh: "Nom de la devise",
    currencySymbolPh: "Symbole devise",
    minWithdrawPh: "Retrait minimum",
    maintenanceMode: "Mode maintenance",
    autoConfirmBookings: "Confirmation auto des réservations",
    autoConfirmBookingsHint:
      "Confirmation immédiate à la réservation (style Planity). L'expert n'accepte pas les RDV. Désactivez seulement pour une validation manuelle par le salon.",
    stripeActive: "Paiement Stripe (activer / désactiver)",
    razorActive: "Paiement Razorpay",
    flutterActive: "Paiement Flutterwave",
    productRequestNew: "Demandes nouveau produit (vendeur)",
    productRequestUpdate: "Mise à jour demandes produit (vendeur)",
    reservationEmailsPh: "Emails notification réservation",
    tabSettings: "Paramètres",
    tabPayments: "Paiements",
    tabWithdraw: "Moyens de retrait",
    stripeSection: "Paiement Stripe",
    mtnSection: "MTN MoMo",
    razorSection: "Razorpay",
    flutterSection: "Flutterwave",
    appSection: "Application",
    mtnApiUserLabel: "API User ID MTN MoMo",
    mtnApiKeyLabel: "Clé API MTN MoMo",
    mtnCallbackLabel: "Hôte de callback",
    mtnEnvLabel: "Environnement",
    mtnEnvSandbox: "Test (sandbox)",
    mtnEnvProduction: "Production",
    mtnActive: "MTN MoMo (activer / désactiver)",
    mtnEnableHint: "Activez ce commutateur après avoir renseigné toutes les clés MTN MoMo ci-dessus.",
    mtnSubKeyHint: "La clé d'abonnement (en-tête Ocp-Apim-Subscription-Key) utilise la clé API si renseignée, sinon la clé primaire.",
    mtnEnabled: "Activé",
    mtnDisabled: "Désactivé",
    addProductRequest: "Demandes nouveau produit",
    updateProductRequest: "Mise à jour demandes produit",
    adminCommissionLabel: "Commission admin produits (%)",
    reservationEmailsLabel: "Emails — notifications réservation",
    firebaseLabel: "Clé Firebase (JSON)",
    invalidJson: "JSON invalide.",
    stripePublishableLabel: "Clé publique Stripe",
    stripeSecretLabel: "Clé secrète Stripe",
    mtnSubscriptionRequired: "La clé d'abonnement MTN MoMo est requise.",
    mtnApiUserRequired: "L'API User ID MTN MoMo est requis.",
    mtnApiKeyRequired: "La clé API MTN MoMo est requise.",
    mtnSubscriptionLabel: "Clé d'abonnement MTN MoMo",
    walletSection: "Portefeuille",
    walletPayActive: "Paiement portefeuille — app cliente (activer / désactiver)",
    walletPayHint:
      "Affiche le portefeuille comme moyen de paiement lors des réservations et achats. Désactivé par défaut pour permettre l'utilisation sans paiement en ligne.",
    salonWalletRechargeActive: "Recharge portefeuille salon (Stripe / MTN MoMo)",
    salonWalletRechargeHint:
      "Affiche la section de recharge du portefeuille dans le panel salon. Désactivé par défaut.",
  },
  appointment: {
    title: "Nouveau rendez-vous",
    onDatePrefix: "Le",
    atTime: "À",
    salon: "Salon",
    expert: "Pro",
    customer: "Cliente",
    chooseDate: "Choisir la date",
    chooseTime: "Choisir l'heure",
    selectSalon: "Choisir le salon",
    selectExpert: "Choisir le pro",
    selectCustomer: "Choisir la cliente",
    salonRequired: "Le salon est requis.",
    expertRequired: "Le pro est requis.",
    customerRequired: "La cliente est requise.",
    clientSince: "Cliente depuis",
    email: "Email",
    uniqueId: "Référence",
    close: "Fermer",
  },
  salonForm: {
    addTitle: "Ajouter un salon",
    editTitle: "Modifier le salon",
    name: "Nom du salon",
    email: "Email",
    mobile: "Téléphone",
    password: "Mot de passe",
    platformFee: "Frais plateforme (%)",
    minWalletBalance: "Solde portefeuille minimum (€)",
    minWalletBalanceHint: "Vide = défaut plateforme. 0 = aucun minimum pour ce salon.",
    address: "Adresse",
    landmark: "Repère",
    city: "Ville",
    state: "Région",
    country: "Pays",
    latitude: "Latitude",
    longitude: "Longitude",
    about: "À propos (fiche publique)",
    mainImage: "Photo principale",
    gallery: "Photos du salon (max. 10)",
    nameRequired: "Le nom est requis.",
    aboutRequired: "La description est requise.",
    emailRequired: "L'email est requis.",
    passwordRequired: "Le mot de passe est requis.",
    platformFeeRequired: "Les frais plateforme sont requis.",
    mobileRequired: "Le téléphone est requis.",
    addressRequired: "L'adresse est requise.",
    landmarkRequired: "Le repère est requis.",
    cityRequired: "La ville est requise.",
    stateRequired: "La région est requise.",
    countryRequired: "Le pays est requis.",
    latitudeRequired: "La latitude est requise.",
    longitudeRequired: "La longitude est requise.",
    imagesRequired: "Au moins une photo est requise.",
    imagesMax: "Maximum 10 photos.",
  },
  coupon: {
    dialogTitle: "Code promo",
    title: "Titre",
    prefix: "Préfixe",
    prefixHint: "Préfixe (ex. FREETIER)",
    description: "Description",
    expiryDate: "Date d'expiration",
    minAmount: "Montant minimum",
    couponType: "Type de code",
    discountType: "Type de remise",
    maxDiscount: "Remise max.",
    discountPercent: "Remise (%)",
    selectCouponType: "Choisir le type",
    selectDiscountType: "Choisir la remise",
    typeWallet: "Portefeuille",
    typeAppointment: "Réservation",
    discountFlat: "Montant fixe",
    discountPercentType: "Pourcentage",
    titleRequired: "Le titre est requis.",
    prefixRequired: "Le préfixe est requis.",
    descriptionRequired: "La description est requise.",
    expiryRequired: "La date d'expiration est requise.",
    couponTypeRequired: "Le type est requis.",
    discountTypeRequired: "Le type de remise est requis.",
    maxDiscountRequired: "La remise max. est requise.",
    discountPercentRequired: "Le pourcentage est requis.",
    discountPercentRange: "Le pourcentage doit être entre 0 et 99.",
    minAmountRequired: "Le montant minimum est requis.",
  },
  alert: {
    title: "Confirmer l'action ?",
    text: "Cette action est définitive.",
    logout: "Se déconnecter",
    logoutTitle: "Se déconnecter ?",
    logoutText:
      "Vous allez quitter l'administration Skedisy. Assurez-vous d'avoir enregistré vos modifications.",
    logoutConfirm: "Se déconnecter",
    logoutCancel: "Rester connecté",
    approveWithdraw: "Valider cette demande de retrait ?",
    approveProduct: "Valider cette demande produit ?",
    rejectRequest: "Refuser cette demande ?",
  },
  toast: {
    success: "Succès",
    error: "Erreur",
    warning: "Attention",
    info: "Info",
    oops: "Oups",
    notice: "Notification",
    missingFile: "Vérifiez les champs requis — fichier manquant.",
    loginOk: "Connexion réussie.",
    taxAdded: "Taxe ajoutée.",
    taxUpdated: "Taxe mise à jour.",
    taxStatus: "Statut taxe mis à jour.",
    taxGeneric: "Taxe mise à jour.",
    passwordUpdated: "Mot de passe mis à jour.",
    adminCreated: "Administrateur créé.",
    codeUpdated: "Code mis à jour.",
    adminUpdated: "Profil mis à jour.",
    salonCreated: "Salon créé.",
    salonUpdated: "Salon mis à jour.",
    salonDeleted: "Salon supprimé.",
    expertCreated: "Pro ajouté.",
    expertUpdated: "Pro mis à jour.",
    expertDeleted: "Pro supprimé.",
    serviceAdded: "Prestation ajoutée.",
    serviceUpdated: "Prestation mise à jour.",
    serviceDeleted: "Prestation supprimée.",
    categoryAdded: "Catégorie ajoutée.",
    categoryUpdated: "Catégorie mise à jour.",
    categoryDeleted: "Catégorie supprimée.",
    categoryStatus: "Statut catégorie mis à jour.",
    bookingCancelled: "Réservation annulée.",
    couponCreated: "Code promo créé.",
    couponDeleted: "Code promo supprimé.",
    settingUpdated: "Paramètres mis à jour.",
    maintenanceUpdated: "Mode maintenance mis à jour.",
    notificationSent: "Notification envoyée.",
    complainSolved: "Réclamation traitée.",
    holidayAdded: "Congé ajouté.",
    holidayDeleted: "Congé supprimé.",
    attendanceUpdated: "Présence mise à jour.",
    updated: "Mis à jour.",
    salaryPaid: "Paiement enregistré.",
    bonusUpdated: "Bonus / pénalité mis à jour.",
    invoiceDownloaded: "Facture téléchargée.",
    invoiceSent: "Facture envoyée.",
    serviceUpdated: "Prestation mise à jour.",
    productDeleted: "Produit supprimé.",
    productCategoryAdded: "Catégorie produit ajoutée.",
    attributeAdded: "Attribut ajouté.",
    attributeUpdated: "Attribut mis à jour.",
    maintenanceUpdated: "Mode maintenance mis à jour.",
    complainSolved: "Réclamation traitée.",
    citiesUpdated: "Villes mises à jour.",
  },
  pages: {
    adminProfile: "Profil administrateur",
    bookings: "Réservations",
    todayPending: "Réservations en attente (aujourd'hui)",
    monthlyReport: "Rapport mensuel",
    salons: "Salons",
    addSalon: "Ajouter un salon",
    experts: "Équipe",
    addExpert: "Ajouter un·e pro",
    customers: "Clientes",
    reviews: "Avis",
    complaints: "Réclamations",
    category: "Catégories",
    services: "Prestations",
    orders: "Commandes",
    products: "Produits",
    coupons: "Codes promo",
    teamCalendar: "Planning équipe",
  },
  analytics: {
    all: "Tout",
    today: "Aujourd'hui",
    yesterday: "Hier",
    last7: "7 derniers jours",
    last30: "30 derniers jours",
    thisMonth: "Ce mois-ci",
    lastMonth: "Mois dernier",
    rangeTo: "au",
    selectDate: "Choisir une date",
  },
  apiMessages: {
    genericError: "Une erreur est survenue.",
    unexpectedError: "Erreur inattendue.",
    invalidCredentials: "Identifiants incorrects.",
    unauthorized: "Session expirée — reconnectez-vous.",
    userNotFound: "Utilisateur introuvable.",
    salonNotFound: "Salon introuvable.",
    expertNotFound: "Pro introuvable.",
    bookingNotFound: "Réservation introuvable.",
    notFoundGeneric: "Élément introuvable.",
    requiredGeneric: "Champs requis manquants.",
    invalidGeneric: "Données invalides.",
    successGeneric: "Opération réussie.",
    insufficientBalance: "Solde insuffisant.",
    withdrawSubmitted: "Demande de retrait envoyée.",
  },
  paymentFields: {
    "upi id": "Identifiant UPI",
    upi: "UPI",
    "ifsc code": "Code IFSC",
    ifsc: "Code IFSC",
    "bank name": "Nom de la banque",
    "account number": "N° de compte",
    "branch name": "Agence",
    "mobile number": "Téléphone",
    email: "Email",
    paypal: "PayPal",
    "pay pal": "PayPal",
    "account holder name": "Titulaire du compte",
    "holder name": "Titulaire du compte",
  },
  paymentMethods: {
    "bank transfer": "Virement bancaire",
    bank: "Banque",
    upi: "UPI",
    paypal: "PayPal",
    razorpay: "Razorpay",
    stripe: "Stripe",
    "mtn momo": "MTN MoMo",
    cash: "Espèces",
  },
  withdraw: {
    title: "Demande de retrait",
    balanceLabel: "Solde disponible",
    amountLabel: "Montant à retirer",
    amountPlaceholder: "Saisir le montant",
    amountMinError: "Le montant doit être au moins",
    amountMaxNote: "Montant minimum de retrait :",
    paymentOption: "Mode de paiement",
    paymentField: "Saisir :",
    paymentFieldPlaceholder: "Votre",
    instructionsTitle: "Comment retirer",
    instructions:
      "Saisissez le montant (minimum indiqué ci-dessus), choisissez votre mode de paiement et renseignez les coordonnées. La demande est traitée par l'équipe Skedisy.",
    amountRequired: "Saisissez un montant.",
    selectPaymentDetail: "Renseignez au moins un détail de paiement.",
    submit: "Demander le retrait",
    bannerAlt: "Retrait des gains",
  },
  labels: {
    bookingType: "Type de réservation",
    selectDate: "Choisir une date",
    selectMonth: "Choisir un mois",
    paymentDate: "Date de paiement",
    addNew: "Ajouter",
    addCategory: "Ajouter une catégorie",
    addService: "Ajouter une prestation",
    addAttribute: "Ajouter un attribut",
    addProductCategory: "Ajouter une catégorie produit",
    category: "Catégories",
    products: "Produits",
    addProducts: "Ajouter un produit",
    productCategory: "Catégorie produit",
    newHoliday: "Nouveau congé",
    todayPendingTitle: "Réservations en attente (aujourd'hui)",
    yearlyPayment: "Historique paiements par année",
    salonPayment: "Paiements salon",
    expertPayments: "Paiements experts",
    expertWithdrawHistory: "Historique retraits pros",
    salonEarnings: "Revenus salon",
    salonOrders: "Commandes salon",
    walletHistory: "Historique portefeuille",
    expertEarningsDetail: "Détail gains pro",
    staffAttendanceData: "Détail des présences",
    selectMonthLabel: "Mois",
    bookingFeeDeduction: "Frais de réservation déduits",
    bookingComplete: "Réservation terminée",
    withdrawPending: "Retrait en attente",
    withdrawApproved: "Retrait validé",
    withdrawDeclined: "Retrait refusé",
    editOrder: "Modifier la commande",
    selectStatus: "Choisir le statut",
    cancelOrderChargesNote: "Frais d'annulation :",
    cannotCancelOrder: "Annulation impossible : le sous-total est inférieur aux frais d'annulation.",
    priceRequired: "Le prix est requis.",
    imagePathRequired: "Le chemin image est requis.",
    imageRequired: "L'image est requise.",
    openTimeRequired: "L'heure d'ouverture est requise.",
    dayRequired: "Le jour est requis.",
    closeTimeRequired: "L'heure de fermeture est requise.",
    dayRequiredBang: "Le jour est requis.",
    slotTimeRequired: "Le créneau est requis.",
    minWithdrawLabel: "Montant minimum de demande de retrait",
    cancelOrderChargesPct: "Frais annulation commande (%)",
    stripeSecretLabel: "Clé secrète Stripe",
    newItems: "Nouveaux articles",
    updatedItems: "Articles mis à jour",
    updateBtn: "Mettre à jour",
    salonBookingsTitle: "Réservations du salon",
    expertsTitle: "Coiffeur·se·s / pros",
    servicesTitle: "Prestations",
    salonTimeTitle: "Horaires salon",
    withdrawMoneyTitle: "Retrait",
    salonWithdrawRequest: "Demandes de retrait salon",
    expertWithdrawRequest: "Demandes de retrait pro",
    productCategoryDialog: "Catégorie produit",
    paymentHistoryTitle: "Historique des paiements",
    bookingsTitle: "Réservations",
    minAmountApply: "Montant minimum",
  },

};
